### ISSUE TITLE
Release version incremented incorrectly 

### ISSUE THREAD

**Issue by intex46** [python-semantic-release/python-semantic-release#1007]
### Description
Hello, 
We use PSR to handle semantic versioning of our api with azure devops,
the incrementation of pre-release version is not incremented on the last release version

### Expected behavior
0.0.1 -> 0.1.0-alpha.1->0.1.0-rc.1->0.1.0 -> 0.1.1-alpha.1

### Actual behavior
0.0.1 -> 0.1.0-alpha.1->0.1.0-rc.1->0.1.0 -> 0.1.0-alpha.2

### Environment

-  **Operating System (w/ version):** ubuntu-latest
-  **Python version:** 3.10
-  **Semantic-release version:** 9.8.7

<details>
<summary><code>pip freeze</code></summary>

```log
annotated-types==0.7.0
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
click-option-group==0.5.6
dotty-dict==1.3.1
gitdb==4.0.11
GitPython==3.1.43
idna==3.7
importlib_resources==6.4.3
Jinja2==3.1.4
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
pydantic==2.8.2
pydantic_core==2.20.1
Pygments==2.18.0
python-gitlab==4.9.0
python-semantic-release==9.8.7
requests==2.32.3
requests-toolbelt==1.0.0
rich==13.7.1
shellingham==1.5.4
smmap==5.0.1
tomlkit==0.13.2
typing_extensions==4.12.2
urllib3==2.2.2
```

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
semantic_release]
logging_use_named_masks = true
tag_format = "{version}"
commit_parser = "angular"
commit_message = "chore(release): release {version} [skip ci]"
remove_dist = true
version_variables = [
    "app/__init__.py:__version__"
]

[semantic_release.remote]
domain = "dev.azure.com" #need to override the value otherwise the generated chengelog.md is false

[semantic_release.changelog]
template_dir = "changelog_template"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = [
    "^wip:.*",  # Exclude commits that start with "wip :"
    "^Merged PR.*", # Exclude Pull Request commits
    "chore"

]

[semantic_release.branches.main]
match = "main"
prerelease = false

[semantic_release.branches.dev]
match = "dev"
prerelease = true
prerelease_token="alpha"

[semantic_release.branches.ta]
match = "ta"
prerelease = true
prerelease_token="rc"
```
<details>
<summary>Azure Devops Job Definition</summary>

```yaml
jobs:
  - job: SemanticVersion
    displayName: 'Bump Semantic version'
    steps:

    - checkout: self
      persistCredentials: "true"
      clean: "true"

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'

    - script: |
        pip install python-semantic-release==9.8.7
      displayName: 'Install dependencies'

    - script: |
        git fetch --unshallow --prune --prune-tags --tags
        git checkout ${{ parameters.BranchName }}
      displayName: 'Git Sync'


    - script: |
        echo "working branch : $(git rev-parse --abbrev-ref HEAD)"
        echo "create semantic versioning for ${{ parameters.BranchName }} ..."
        if [[ ${{ parameters.BranchName }} != "main" ]]; then
          semantic-release -vv -c releaserc.toml version --as-prerelease --push --no-vcs-release --no-changelog
        else
          semantic-release -vv -c releaserc.toml version --push --no-vcs-release
        fi
```
### Execution Log

<summary><code>semantic-release -vv <i>-c releaserc.toml version --as-prerelease --push --no-vcs-release --no-changelog</i></code></summary>

```log
  
```
