### ISSUE TITLE
Automatic Release for GitLab

### ISSUE THREAD

**Issue by t11c** [python-semantic-release/python-semantic-release#1008]
## Question
Hi, is anyone doing automatic releases for GitLab? This worked flawlessly <v8.0. Maybe I get this wrong but as far as I understand the docs, automatic releases with GitLab don't work out of the box now. Has anyone managed to do this? I wonder how would it work?
Thanks!

**Comment by codejedi365** [comment]
GitLab does work out of the box and many people are using it. What seems to be your problem?

The biggest error that normally occurs is people try to use the CI_JOB_TOKEN and it has not had permissions to write to the repository until GitLab 17.2. You must use a Project, Group, or Personal Access Token as described on the first page of the documentation.

I have not had time to complete #977 for CI_JOB_TOKEN compatibility.

**Comment by t11c** [comment]
OK, thanks! actually I don't know what I did wrong in the first place, I guess I just assumed from the Docs that Gitlab releases weren't supported and gave up after encountering the first error. 

Now I just went over the `.gitlab-ci.yml`, `pyproject.toml`, added the token to the ci/cd variables, and it works! that's great :-)

heres' the my build stage, I guess not best practice but maybe it's helpful for someone:


```yml
build:
    stage: build
    variables:
        # see https://github.com/python-semantic-release/python-semantic-release/issues/415#issuecomment-1048181466
        GIT_STRATEGY: clone
    only:
        - main
    script:
        # Set up virtual environment and configurations
        - pipenv --venv
        - apt-get install git -y
        - git config --global user.name "semantic-release"
        - git config --global user.email "semantic-release@gitlab"

        # Checkout the current branch to prevent a detached head
        - git checkout $CI_COMMIT_BRANCH    #REF_NAME  # checkout current commit to prevent a detached head, see https://github.com/python-semantic-release/python-semantic-release/issues/627

        # Set the remote URL
        - git remote set-url origin "https://__token__:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"

        # Fetch all Tags in order to create a full CHANGELOG
        - git fetch --tags --force

        # Debug: print the last commit messages
        - echo "Last 10 commit messages:"
        - git log -n 10 --pretty=format:"%h - %s"

        # Install python-semantic-release
        - python3 -m pip install python-semantic-release build

        # Debugging information
        - pwd
        - ls -l
        - semantic-release --version

        # Create release and commit changes without pushing
        - semantic-release -v version

        # Check the status of the git repository
        - git status

        # Push changes to the current branch
        - git push origin $CI_COMMIT_BRANCH --follow-tags

        # Check the status again to ensure everything is up to date
        - git status

        # Check if there are files in the /dist folder
        - if [ "$(ls -A dist)" ]; then
            echo "Build artifacts found in /dist. Proceeding with package upload.";
            TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token pipenv run twine upload --skip-existing --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*;        
          else
            echo "No build artifacts found in /dist. Skipping package upload.";
          fi
```
