### ISSUE TITLE
Repository files changed during the `build_command` are not being properly committed back to the repo

### ISSUE THREAD

**Issue by nfelt14** [python-semantic-release/python-semantic-release#1010]
### Description

I am trying to automate updating version numbers in GitHub actions usage when a new build is created by using a custom script that is part of the `build_command`.

### Expected behavior

I expected the changed files to be committed back to the repo along with the version change in the `pyproject.toml` file.

### Actual behavior

The changed files were not committed back to the repo.

### Environment

GitHub workflow run: https://github.com/tektronix/python-package-ci-cd/actions/runs/10584124298/job/29327658232
### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
build_command = """
  python -m scripts.bump_version_in_files
"""
version_toml = [
  "pyproject.toml:tool.poetry.version"
]

[tool.semantic_release.changelog]
exclude_commit_patterns = []
template_dir = "python_semantic_release_templates"

[tool.semantic_release.changelog.environment]
extensions = []

[tool.semantic_release.commit_parser_options]
# These settings allow python-semantic-release to be used without triggering on any commits
allowed_tags = []
minor_tags = []
patch_tags = []
```

</details>
<br>

<details>
<summary>GitHub Actions Job Definition</summary>

```yaml
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.8.7
        id: release
        with:
          force: ${{ inputs.release-level }}
          root_options: -v --strict
          github_token: ${{ secrets.checkout-token }}
          git_committer_email: ${{ inputs.commit-user-email }}
          git_committer_name: ${{ inputs.commit-user-name }}
```

</details>

### Execution Log

<details>
<summary><code>semantic-release -vv version --patch</code></summary>

[command_output.txt](https://github.com/user-attachments/files/16768121/temp_.txt)

</details>
