### ISSUE TITLE
Allow github version bump commit to use a PAT token instead of ssh_public_signing_key

### ISSUE THREAD

**Issue by manueleiria** [python-semantic-release/python-semantic-release#1017]
### Description
Allow github version bump commit to use a PAT token instead of requiring ssh_public_signing_key and ssh_private_signing_key to be passed to it.

### Use cases
I'm using a Github App to take care of my releases, because otherwise I would have to tie the releases to a particular user. However, the github action expects me to pass ssh_public_signing_key and ssh_private_signing_key for signing, but I can only obtain the ssh_private_signing_key for a Github App.

Additionally, I have checked that when specifying `[skip ci]` I can trigger pipelines that run on `push` for tagged commits only when said commit has been verified (please refer to [this comment on issue 973](https://github.com/python-semantic-release/python-semantic-release/issues/973#issuecomment-2213244824) for additional for additional considerations on the `[skip ci]` flag).. For instance, if I have updated the pyproject.toml manually, then python-semantic-version will skip the commit, but still create the tag and the release, in which case the pipeline for the tag still runs (as intended). However, if I let python-semantic-version do the commit, it will be pushed without verification and it won't trigger the `on push` pipeline for tags.

### Possible implementation
If I could instead pass a PAT token, I could generate one ad-hoc PAT for the Github App bot and pass that instead.

**Comment by codejedi365** [comment]
Hello @manueleiria,

I feel I do not understand your request, likely because I don't know much about a GitHub App.  First off, the `ssh_public_signing_key` and `ssh_private_signing_key` are not required fields for the GitHub Action--they are optional [`action.yml`]().  Secondly, they are used for signing the commit and signing the tag within git.  

I assume you have rules in place on your repository that restrict from "non-verified" commits in the repository. This would mean non signed tags or commits.  I assume this is why you desire to use ssh signing to make digitally identified commits which is currently the only method supported inside of the PSR GitHub Docker Action.

This is where I get lost. I don't know how a Personal Access Token (PAT) provides you signed commits or tags?

As the GitHub Action is a lot more restrictive to how you use PSR, might I recommend instead running PSR normally via command line.  This way you are outside of the docker environment and you can configure the git repository however you would like to create signed commits.

**Comment by manueleiria** [comment]
Hi @codejedi365! So, to try to answer some of your points:

> I feel I do not understand your request, likely because I don't know much about a GitHub App. First off, the ssh_public_signing_key and ssh_private_signing_key are not required fields for the GitHub Action--they are optional [action.yml](https://github.com/python-semantic-release/python-semantic-release/blob/v9.8.8/action.yml). Secondly, they are used for signing the commit and signing the tag within git.

I'm aware of their optionality. The thing I've noticed however in many of my runs is that the release is created with the owner of token I passed in github_token, but the commit with the changes gets pushed with semantic-release as it's author. I've been able to change this by passing `git_committer_name` and `git_committer_email`. However, the signing key is required for signing those commits.

Now, I would prefer not to have the private and public signing keys as secrets, since they are bound to a particular user. Github allows you to create Apps, which can really just be a way to have a service account bound to your organization and that you can use to do specific push actions that aren't bound to the repository's `GITHUB_TOKEN`. This is because only `dispatch` type workflows can be triggered by events using `GITHUB_TOKEN` ([see here](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)).
The particular thing about Github Actions is that you can generate a private ssh key, but they don't expose the public key, so there's no way for me to sign the commit using the Github Action with the available method using a Github App. It's possible for me to generate a temporary PAT for the Github App, and that's what I would like to use instead for the signing bit.

> I assume you have rules in place on your repository that restrict from "non-verified" commits in the repository. This would mean non signed tags or commits. I assume this is why you desire to use ssh signing to make digitally identified commits which is currently the only method supported inside of the PSR GitHub Docker Action.

We haven't set up any restriction for this. Do note the following screenshots on the release page:

![image](https://github.com/user-attachments/assets/885851ac-b056-4eb4-a5a7-986366da47eb)
![image](https://github.com/user-attachments/assets/f9578b6f-74ed-4dc5-baec-6f90e888b8f8)
![image](https://github.com/user-attachments/assets/bf4c7fe4-a48c-4bc9-bef6-68021cdce591)

This first one is a release where the pyproject.toml version was bumped manually. Note on line 64 how the commit was skipped. My version specific pipeline is executed afterwards.

![image](https://github.com/user-attachments/assets/a9c110ae-ca0a-430e-ba5c-c8967d97c3ec)
![image](https://github.com/user-attachments/assets/22464d70-9278-42a6-86bc-a1e18c7541a7)
![image](https://github.com/user-attachments/assets/0cfe05be-65ea-4e11-81e3-7c120aa2359e)

In the second case the commit isn't skipped, and in fact the release commit is the one after the commit of the workflow execution. My version specific pipeline isn't executed afterwards.

<details>
<summary>First workflow</summary>

  ```yml
---
name: Test & Release

on:
  push:
    branches-ignore: # Consider not ignoring branches and just ignoring unnecessary jobs when branch is not dev, staging or main
      - 'feature/*'

concurrency:
  group: push-${{ github.ref }}

env:
  OUTPUT_PATH: "out"
  TESTS_PATH: "tests"
  LINT_RESULTS_FILE: "flake8.txt"
  JUNIT_RESULTS_FILE: "junit.xml"
  COVERAGE_RESULTS_FILE: "coverage.xml"

jobs:
  commit-lint:
    name: Check Commit Message
    runs-on: [ubuntu-latest, ephemeral]
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commit Lint
        uses: actions/wagoid_commitlint-github-action@v6
  
  lint-and-test:
    name: Lint and Test
    runs-on: [ubuntu-latest, ephemeral]
    needs: commit-lint
    outputs:
      result: ${{ steps.tests.outputs.report }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
        with:
          python-version: "3.10"
          poetry-version: "1.8.3"
      
      - name: Lint
        uses: ./.github/actions/execute-lint
        with:
          flake8-output-path: ${{ env.OUTPUT_PATH }}
          flake8-output-filename: ${{ env.LINT_RESULTS_FILE }}
      
      - name: Tests
        id: tests
        uses: ./.github/actions/execute-tests
        with:
          tests-path: ${{ env.TESTS_PATH }}
          reports-output-path: ${{ env.OUTPUT_PATH }}
          junit-output-filename: ${{ env.JUNIT_RESULTS_FILE }}
          coverage-output-filename: ${{ env.COVERAGE_RESULTS_FILE }}
  
  sonar-scan:
    name: Sonarqube Scan
    runs-on: [ubuntu-latest, ephemeral]
    environment: ${{ github.ref_name }}
    needs: lint-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ${{ env.OUTPUT_PATH }}/
      
      - name: Run Sonarqube Scan
        uses: actions/Sonarsource_sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_URL }}

  scan-container-image:
    name: Scan Container Image
    runs-on: [ubuntu-latest, ephemeral]
    environment: ${{ github.ref_name }}
    needs: sonar-scan
    outputs:
      result: ${{ steps.build-scan.outputs.scan-report }}
      scan-id: ${{ steps.build-scan.outputs.scan-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Scan Container Image
        id: build-scan
        if: ${{ vars.ISS_SCAN_ENABLED == 'true' }}
        uses: ./.github/actions/build-docker-container
        with:
          scan-container: true
          image-name: ${{ vars.PROJECT_NAME }}
          registry-url: ${{ vars.ISS_URL }}
          registry-repo: ${{ vars.ISS_REPO }}
          registry-username: ${{ secrets.ISS_USER }}
          registry-token: ${{ secrets.ISS_TOKEN }}
          csc-token: ${{ secrets.CSC_TOKEN }}

  release:
    name: Release Package
    runs-on: [ubuntu-latest, ephemeral]
    environment: ${{ github.ref_name }}
    needs: scan-container-image
    permissions:
      # https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#metadata
      id-token: write
      contents: write
    outputs:
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - name: Generate release-bot token
        id: generate-token
        uses: actions/tibdex_github-app-token@v2
        with:
          app_id: ${{ secrets.RELEASE_BOT_ID }}
          private_key: ${{ secrets.RELEASE_BOT_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
        with:
          python-version: "3.10"
          poetry-version: "1.8.3"

      - name: Python Semantic Release
        id: release
        uses: actions/python-semantic-release_python-semantic-release@v9.8.7
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          git_committer_name: ${{ secrets.RELEASE_BOT_NAME }}
          git_committer_email: ${{ secrets.RELEASE_BOT_EMAIL }}
          ssh_private_signing_key: ${{ secrets.RELEASE_BOT_KEY }}

  ```
</details>

<details>
<summary>Tag commit workflow</summary>

```yml
---
name: Deploy

on:
  push:
    tags:
      - 'v*'
      # - '!v*-rc*'
      # - '!v*-alpha*'

concurrency:
  group: push_tag-${{ github.ref }}

jobs:
  get-branch:
    name: Get Branch
    runs-on: [ubuntu-latest, ephemeral]
    outputs:
      branch: ${{ steps.get_branch.outputs.branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch
        id: get_branch
        run: |
          branch_name=$(git branch -r --contains ${{ github.ref_name }} | head -n1 | cut -c3- | sed 's/origin\///g;s/HEAD -> //g')
          echo "$branch_name"
          echo "branch=$branch_name" >> $GITHUB_OUTPUT

  deploy-container-image:
    name: Deploy Container Image
    runs-on: [ubuntu-latest, ephemeral]
    needs: get-branch
    environment: ${{ needs.get-branch.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Publish Docker container
        id: build-scan
        uses: ./.github/actions/build-docker-container
        with:
          image-name: ${{ vars.PROJECT_NAME }}
          registry-url: ${{ vars.ARTIFACTORY_URL }}
          registry-port: ${{ vars.ARTIFACTORY_PORT }}
          registry-repo: ${{ vars.ARTIFACTORY_REPO }}
          registry-username: ${{ secrets.ARTIFACTORY_USER }}
          registry-token: ${{ secrets.ARTIFACTORY_TOKEN }}

  create-pull-request:
    name: Create Pull Request
    runs-on: [ubuntu-latest, ephemeral]
    needs: [get-branch, deploy-container-image]
    environment: ${{ needs.get-branch.outputs.branch }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Generate release-bot token
        id: generate-token
        uses: actions/tibdex_github-app-token@v2
        with:
          app_id: ${{ secrets.RELEASE_BOT_ID }}
          private_key: ${{ secrets.RELEASE_BOT_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Pull Request Branch
        id: base-ref
        run: |
          if [[ "${{ needs.get-branch.outputs.branch }}" == "${{ vars.DEV_BRANCH }}" ]]; then
            if [[ "${{ vars.STAGING_BRANCH }}" != '' ]]; then
              github_base_ref="${{ vars.STAGING_BRANCH }}"
            else
              github_base_ref="${{ vars.PROD_BRANCH }}"
            fi
          elif [[ "${{ needs.get-branch.outputs.branch }}" == ${{ vars.STAGING_BRANCH }} ]]; then
            github_base_ref="${{ vars.PROD_BRANCH }}"
          fi
          echo "branch=$github_base_ref" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = "${{ steps.base-ref.outputs.branch }}";
            const head = "${{ needs.get-branch.outputs.branch }}";
            const title = `Merge ${head} into ${base}`;
            const body = `This PR merges changes from ${head} into ${base}.`;

            // Check if a pull request already exists
            const { data: pullRequests } = await github.rest.pulls.list({
              owner,
              repo,
              head: `${owner}:${head}`,
              base
            });

            if (pullRequests.length === 0) {
              // Create a new pull request
              await github.rest.pulls.create({
                owner,
                repo,
                title,
                head,
                base,
                body
              });

              console.log(`Pull request created from ${head} to ${base}.`);
            } else {
              console.log(`Pull request already exists from ${head} to ${base}.`);
            }
```
</details>

<details>
<summary>Semantic Release config</summary>

```toml

[tool.semantic_release]
commit_message = "chore(release): v{version} [skip ci]"
major_on_zero = false
tag_format = "v{version}"
version_source = "tag"
version_toml = [ "pyproject.toml:tool.poetry.version" ]

[tool.semantic_release.changelog]
exclude_commit_patterns = [
  '''chore(?:\([^)]*?\))?: .+''',
  '''ci(?:\([^)]*?\))?: .+''',
  '''refactor(?:\([^)]*?\))?: .+''',
  '''style(?:\([^)]*?\))?: .+''',
  '''test(?:\([^)]*?\))?: .+''',
  '''build\((?!deps\): .+)''',
  '''Merged? .*''',
  '''Initial Commit.*''',
  # Old semantic-release version commits
  '''^\d+\.\d+\.\d+''',
]

[tool.semantic_release.branches."main"]
match = "main"
prerelease = false

[tool.semantic_release.branches."staging"]
match = "staging"
prerelease = true
prerelease_token = "rc"

[tool.semantic_release.branches."dev"]
match = "dev|feature"
prerelease = true
prerelease_token = "alpha"
```
</details>

**Comment by manueleiria** [comment]
I did some additional testing, and I understood finally how to have only one of the pipelines run without the `skip ci` option, by using a `paths-ignore` filter for the pyproject.toml. As such, my usecase is mostly fixed, but the feature request remains: I'd still like that the action be able to be signed by the bot. Unfortunately it is more complicated to implement than I though, since signing cannot be done via PATs, only via GPG keys or using the [GitHub API](https://docs.github.com/en/rest/git/commits?apiVersion=2022-11-28#create-a-commit).

And in fact, only the latter solution is valid for GitHub Apps, since you can't create GPG keys for them.

**Comment by codejedi365** [comment]
@manueleiria, sorry for the delay, ive been under the weather all week. I'm glad you have found some improvements to your way forward. I think the one piece of knowledge that gets you all the way is that you can derive the public key from the private key you are provided. 

```sh
ssh-keygen -y -f key.pem > key.pub
```
Ref: [StackOverflow](https://stackoverflow.com/a/5246045).

Hopefully this helps resolve your use case.

**Comment by wyardley** [comment]
FWIW, if you're trying to do what I think you're trying to do here, I've had some success with this method:

```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        # Set at org level
        app-id: ${{ vars.FOO_APP_ID }}
        # Set at repo level, though could be at org level too if preferred
        # The key here needs to be the private key of the GH app.
        private-key: ${{ secrets.FOO_PRIVATE_KEY }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.generate-token.outputs.token }}
        fetch-depth: 0
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ steps.generate-token.outputs.token }}
```

Note: to get the app ID for the committer email, you can't use the app ID that shows up in the app configuration, but you can hit: [https://api.github.com/users/your-app[bot]](https://api.github.com/users/your-app%5Bbot%5D)
to get the app ID (which you can then put in an email, like NNNNNNNN+your-app[bot]@users.noreply.github.com

(or use [this fancy way](https://github.com/actions/create-github-app-token?tab=readme-ov-file#configure-git-cli-for-an-apps-bot-user).

See
https://github.com/orgs/community/discussions/13836#discussioncomment-2901138
and
https://github.blog/changelog/2022-05-17-consistently-allow-github-apps-as-exceptions-to-branch-protection-rules/
