### ISSUE TITLE
How to modify the tag_format for release and release candidates.

### ISSUE THREAD

**Issue by garrethcain** [python-semantic-release/python-semantic-release#1022]
## Question

I'm trying to build a CICD for BitBucket and using PSR for automated versioning.
The issue I have is that BitBucket uses globs to identify the tags which makes it hard to separate between release and release candidate tags.

For Example;

An RC would look like `0.0.1-rc.1` and a release would look like `0.0.1`.

My BitBucket pipeline looks something like;
```
  tags:
    'v*.*.*-rc.*':
      - step:
          name: Deploy release candidate to staging
          script:
            - ...
     'v*.*.*':
       - step:
       - name: Deploy release to production
       - script:
         - ...
```

The trailing `*` on the second pipeline matches the first pipeline too, which is not ideal as it would release RCs to prod. 😨 

### Configuration

My configuration is currently pretty standard. I'm not sure how to even start to achieve what I'm after.

```toml
[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
no_git_verify = false
tag_format = "v{version}"
version_variables = ["version.py:__version__"]

[tool.semantic_release.branches.staging]
match = "^staging$"
prerelease_token = "rc"
prerelease = true

[tool.semantic_release.branches.master]
match = "^master$"
prerelease = false
```

## Additional context
I think what I'm after something like distinct `tag_format` values for different branches, for example;

```toml
[tool.semantic_release.branches.staging]
  match = "^staging$"
  prerelease_token = "rc"
  prerelease = true
  tag_format = "rc/v{version}"

[tool.semantic_release.branches.master]
  match = "^master$"
  prerelease = false
  tag_format = "release/v{version}"
```

This seems like an obvious requirement so possibly the solution was completely missed when reading the docs. It's also possible the solution is on the BitBucket side, but I haven't been able to find one there either.
