### ISSUE TITLE
Unexpected failure with version command

### ISSUE THREAD

**Issue by clarkecheckr** [python-semantic-release/python-semantic-release#1046]
## Question
I need some help troubleshooting an issue I'm having. Versioning is working great up until the point where psr tries to create the version tag. 

- The merge request runs the pipeline successfully but does not create a version - good
- The merge to main runs the pipeline where the only changes are the commits - good
- The pipeline is run for the version creation and pyproject.toml/GHANGELOG.md are modified - good
- Version tag is created and the pipeline run and fails. - bad

![image](https://github.com/user-attachments/assets/72b75cc0-95bb-400e-b6dd-ddf1beacd542)

The failure just says `ERROR: Job failed: exit code 1` with no other clue as to what's wrong.

![image](https://github.com/user-attachments/assets/b3ba901d-75c9-4c3a-8afb-5951612922a3)

How do I further troubleshoot this?

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
version_variables = ["pyproject.toml:version"]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease = false

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.remote]
type = "gitlab"
```

</details>

**Comment by codejedi365** [comment]
Hi @clarkecheckr, the primary issue is actually right there on line 142. You are in a detached head state. Because of this, we cannot determine which release branch configuration to use and therefore we give up (not ideal, I know but the best I have at the moment).

GitLab uses a detached head state in the way they checkout a small git tree to make it faster to execute the pipelines as most do not need the entire git tree. PSR does need the full git tree as well as being checked out to a specific branch.

My recommendation is you should run the following:

```sh
git fetch --unshallow --prune-tags --prune --all --force

git checkout -B $CI_COMMIT_BRANCH HEAD

semantic-release -vv version
```

**Comment by clarkecheckr** [comment]
Thanks for the prompt response. I didn't think the detached head state was the issue as I get a similar message in my branch yet there's no error.

![image](https://github.com/user-attachments/assets/1e0ca0e5-3f2a-4071-b738-50357123882b)

I'll try these changes and report back.

**Comment by clarkecheckr** [comment]
I'm working on a repo that is just for getting this working in Gitlab and have an absolute minimal configuration for psr. I'd like to contribute my working .gitlab-ci.yml and pyproject.toml configuration to be used as an example in the docs as they would have helped me out immensely. How would I go about that?

**Comment by codejedi365** [comment]
I'm not sure how it isn't a problem in your branch environment as a detached head state is an immediate abort for semantic release

**Comment by clarkecheckr** [comment]
It's not a detached head, it's just the same message that the branch isn't in any release groups.

**Comment by codejedi365** [comment]
Well that message is at the exact same part of the code, it is also an immediate abort

**Comment by codejedi365** [comment]
> I'm working on a repo that is just for getting this working in Gitlab and have an absolute minimal configuration for psr. I'd like to contribute my working .gitlab-ci.yml and pyproject.toml configuration to be used as an example in the docs as they would have helped me out immensely. How would I go about that?

Generally for a GitHub contribution, you would fork the repository, create a branch on your fork, make your changes and then open a PR from your fork's branch to this repo's master branch. The docs are in the docs folder.

However, I have a GitLab instruction guide in the works (70% complete) but I haven't published it yet. Ultimately I will have an examples section in that area like I do for github-actions (docs/automatic-releases/github-actions.rst).

If you want to just put your examples in a gitlab.rst in that folder and explain the rationale, then I will fold yours into my format.

**Comment by clarkecheckr** [comment]
BTW, `git checkout -B $CI_COMMIT_BRANCH` fails with the error `fatal: 'HEAD' is not a valid branch name`. I get the idea and I'm looking up a way to do it.

**Comment by clarkecheckr** [comment]
Also, it only fails for the tag build.

![image](https://github.com/user-attachments/assets/4b93cc41-6170-46d4-9f20-5f59b893711a)

![image](https://github.com/user-attachments/assets/225a2980-158f-4b5c-b1a6-b640065baef8)

**Comment by clarkecheckr** [comment]
The reason this is happening on the tag creation is that the value of `$CI_COMMIT_BRANCH` is "", so the command reads `git checkout -B HEAD` and that's not valid. I tried to add a rule to the .gitlab-ci.yml, but then my pipeline didn't run at all, so I have a little work to do to figure this out.

**Comment by clarkecheckr** [comment]
Adding a rule to skip the pipeline if `$CI_COMMIT_BRANCH` is null kinda worked, but now I'm not creating a tag. I thought maybe it would create the tag, just not run the pipeline but that's not the case.

![image](https://github.com/user-attachments/assets/0695d756-576c-47c5-801e-819d4ebed043)

`stages:
  - release

variables:
  GITLAB_TOKEN: $gitlab_pat

release:
    stage: release
    image: python:latest
    before_script:
      - pip install python-semantic-release
    script:
      - git fetch --unshallow --prune-tags --prune --all --force
      - git checkout -B $CI_COMMIT_BRANCH HEAD
      - semantic-release -v version
    rules:
      - if: $CI_COMMIT_BRANCH != null
`

**Comment by clarkecheckr** [comment]
I was able to get this working with the following config. The reason it was failing when using `git checkout -B $CI_COMMIT_BRANCH HEAD` was because when we get to the tag creation step the value of `$CI_COMMIT_BRANCH` is null. The following config checks to see if it's null, if it is then we set the variable to `$CI_COMMIT_REF_NAME` otherwise we use `$CI_COMMIT_BRANCH`.  This seems to work but I will be testing it more to confirm. Can you see anything wrong with this method?
```
stages:
  - release

variables:
  GITLAB_TOKEN: $gitlab_pat

release:
    stage: release
    image: python:latest
    before_script:
      - pip install python-semantic-release
    script:
      - git fetch --unshallow --prune-tags --prune --all --force
      - echo "CI_COMMIT_REF_NAME" $CI_COMMIT_REF_NAME
      - git checkout -B $SOURCE_BRANCH HEAD
      - semantic-release -v version
    rules:
      # if the commit branch is not null, use the commit branch name
      - if: $CI_COMMIT_BRANCH != null
        variables:
          SOURCE_BRANCH: $CI_COMMIT_BRANCH
      # if the commit branch is null, use the commit ref name
      # this is to account for the fact that the version tag has a null value for $CI_COMMIT_BRANCH
      - if: $CI_COMMIT_BRANCH == null
        variables:
          SOURCE_BRANCH: $CI_COMMIT_REF_NAME
```

**Comment by codejedi365** [comment]
@clarkecheckr, sorry I was unavailable while you worked the issue.  

There isn't anything particularly wrong with your approach but I can't say it would be my way I would solve the problem.  I will try to provide some conceptual rationale behind my approach first. In my solution, I utilize `workflow:rules` to restrict the types of pipelines that occur.  I generally recommend to never run semantic-release on a tag triggered pipeline.  This defeats the purpose of using `semantic-release`.  The idea behind PSR and conventional commit strategies is to eliminate the emotional attachment to release versions, which crudely means no human makes a tag anymore--PSR handles that based on what you documented that changed. Secondly, I think its a bit of a waste of resources to spin up another pipeline which has no comprehension of what was accomplished prior to the tagged release and rather just set a deploy stage (set of deploy jobs, many times there is more than one deployment target) that is dependent on release job outcomes.

Also note, that I generally use GitHub Flow branching strategy coupled with a Squash commit merge strategy and in my projects, I rarely create pre-releases (more of a result of my environment, but small amount of preference). Lastly, I haven't done too much of multi-version release support (ie v2 in maintenance, v3 is stable, v4 is unstable) so my example below doesn't handle this.

So in my workflows, I run when there is a (1) push to the default branch, (2) a merge request event, (3) a pipeline source that is manual or deliberately triggered.  Regardless of the workflow trigger, I run a check stage that simultaneously runs a build, code linting, commit-linting, unit testing. Then I move into a test stage which focuses on runtime (system, integration, etc) testing. If this is a MR/PR, then the pipeline ends.  If it is the push to the default branch (ie my release branch), then release job & deploy jobs are enabled depending on if I either set it to manually be triggered or allow auto-delivery/deployment. The release job is using semantic-release to determine if a release is required and then the deployment jobs depend on the result of that job.

<details>
<summary>Python Semantic Release Configuration</summary>

```toml
[tool.semantic_release.branches.release]
match = "^(main|master)$"
prerelease = false

[tool.semantic_release.branches.other]
# Used for enabling build jobs during PRs where a pre-release version is created on any
# branch name but not published (ie. internal use from workflow artifacts)
match = ".*"
prerelease_token = "dev"
prerelease = true

[tool.semantic_release.remote]
type = "gitlab"
ignore_token_for_push = true
token = { 'env': "GITLAB_TOKEN" }
```

<details>

<details>
<summary>GitLab Workflow</summary>

```yaml
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE =~ "/api|web|schedule|web|trigger|pipeline/"'
    - when: never


stages:
  - .pre
  - check
  - test
  - release
  - deploy


commit-lint:
  stage: check


build:
  stage: check
  needs: 
    - job: commit-lint
  script: 
    - git fetch --unshallow --prune-tags --prune --all --force
    - git checkout -B "$CI_COMMIT_BRANCH" HEAD
    - semantic-release version --no-commit --no-tag 
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 week


test:
  stage: test


release:
  stage: release
  rules:
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH'
      when: manual       # <--- leave this out if you want auto-deployment
  allow_failure: false      # must have when it is set to manual otherwise GitLab will move on to deploy
  environment:
    name: repository       # custom environment that holds the PAT (and only available to this job)
  script:
    - git fetch --unshallow --prune-tags --prune --all --force
    - git checkout -B "$CI_COMMIT_BRANCH" HEAD
    - semantic-release -vv version --skip-build


deploy-gl-pypi:
  stage: deploy
  needs:
    - job: release
    - job: build
      artifacts: true
  rules:
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH'
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
  script:
    - twine upload --repository-url "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi" dist/*
```
</details>

One additional nuance that I do is actually run semantic-release in the build job but in a non-persistent way because I can gain the nicety to only have to have 1 place where the build command is defined. Secondly when building the artifact (versions stamped and everything) at the beginning of the pipeline I can now actually test the exact (hashed) item that is to be released. Generally, using semantic-release to build at the end actually builds a new artifact (hashes are different) that wasn't tested--many people wave this risk.

**Comment by codejedi365** [comment]
If you are going to do a full auto-delivery/deployment you may want to adjust the release job slightly to handle the edge case of when a new version is not required.

```yaml
release:
  stage: release
  rules:
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH'
  environment:
    name: repository       # custom environment that holds the PAT (and only available to this job)
  script:
    - git fetch --unshallow --prune-tags --prune --all --force
    - git checkout -B "$CI_COMMIT_BRANCH" HEAD
    - if semantic-release -vv version --strict --print; then
         semantic-release version --skip-build;
      else
         printf '%s\n' "PSR_RELEASED=false" >> deploy.env;
      fi
  artifacts:
    reports:
      dotenv: deploy.env

deploy-gl-pypi:
  stage: deploy
  needs:
    - job: release
    - job: build
      artifacts: true
  rules:
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH'
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
  script:
    - if [ "PSR_RELEASED" = "true" ]; then
        twine upload --repository-url "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi" dist/*;
      fi
```

Its not pretty but it does show that the pipeline jobs never fail (on a no release) because they did work as intended and no need for human intervention or review. OR you can just have the deploy fail when the version has not been bumped. It's a matter of preference.

**Comment by clarkecheckr** [comment]
No worries about the delay, and thank you for the very detailed answer. This gives me a lot to work with and I'll be digesting it and rolling some of these concepts into my project as I implement this. Initially I was just trying to get things to work without errors, but now that that's happening I will be working to make it what I need it to be given my environment.

**Comment by codejedi365** [comment]
Good to hear, and I'm glad it provides some value to you. Let me know if you have further questions as I could have made a typo (and I left out some job implementations for simplicity) as I was transplanting my answer.

**Comment by clarkecheckr** [comment]
I thought I saw this in the documentation, but can't find it now. Is it possible to force semver comment syntax? Maybe fail the pipeline if the syntax is wrong or comment is missing? As I understand it if it's not the right syntax, there just isn't a version created.

**Comment by codejedi365** [comment]
> I thought I saw this in the documentation, but can't find it now. Is it possible to force semver comment syntax? Maybe fail the pipeline if the syntax is wrong or comment is missing? As I understand it if it's not the right syntax, there just isn't a version created.

At this time there is nothing built into PSR to validate commit syntax. For those using the angular parser, my recommendation is to use already published `commit linting` tools that adhere to the same syntax standards. One such tool is [`commitizen`](https://commitizen-tools.github.io/commitizen/) and the use of the `check` subcommand. There is also a few GitHub actions that do it as well but may use the JS version of commitizen. Luckily the standard is set by conventional-commits.org which all the tools implement.

**Comment by daniel-albuschat** [comment]
Hi @codejedi365,

from what I understand, I think every GitLab CI is cloning repose with a detached head, so every user of python-semantic-release in GitLab CI would need to apply this workaround:

> ```shell
> # make sure you have the full accurate history
> git fetch --unshallow --prune-tags --prune --all --force
> 
> # make sure the branch Head is at the commit that was tested/started the workflow
> git checkout -B $CI_COMMIT_BRANCH HEAD
> 
> semantic-release -vv version
> ```

If my understanding is correct, wouldn't it be great if python-semantic-release would automatically do this?

(Additionally: `git fetch --unshallow` bails out in my case with the error message `fatal: --unshallow on a complete repository does not make sense`. Maybe because the repo has a very small commit history.)

Greetings,

Daniel Albuschat

**Comment by daniel-albuschat** [comment]
> (Additionally: `git fetch --unshallow` bails out in my case with the error message `fatal: --unshallow on a complete repository does not make sense`. Maybe because the repo has a very small commit history.)

I've replaced `--unshallow` with `--depth=2147483647`, and this seems to help.

**Comment by codejedi365** [comment]
@daniel-albuschat, I haven't gotten around to that but I did have it as an action item one of these days. 

There is a way to check if the repo is already unshallowed and should be inluded as a bash conditional before the execution but I can't remember what it is at the moment. Will check later.

**Comment by cfxegbert** [comment]
Sorry about commenting on a closed issue.  There are mechanisms in GitLab to clone the whole repository instead of doing a shallow clone.  You can do
```yaml
release:
  stage: release
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"
...
```
instead of
```yaml
release:
  stage: release
  script:
    - if git rev-parse --is-shallow-repository | grep -q "true"; then
         git fetch --unshallow --prune-tags --prune --all --force;
      fi
...
```

See:
  - https://docs.gitlab.com/ee/ci/pipelines/settings.html#choose-the-default-git-strategy
  - https://docs.gitlab.com/ee/ci/pipelines/settings.html#limit-the-number-of-changes-fetched-during-clone
  - https://docs.gitlab.com/ee/ci/runners/configure_runners.html#configure-runner-behavior-with-variables

**Comment by codejedi365** [comment]
@cfxegbert, it's a good thing to note for others. Do you know which version of GitLab that was introduced? I feel like it was pretty recent.

Also can you validate that it actually prunes or clones all the tags if the build directory is cached? That is a problem I had with GitLab was that deleted tags do not get cleaned up from a repo without `--prune-tags`.

**Comment by cfxegbert** [comment]
The GIT_ variables have been available for several years.  I've been using it for over 3 years.  The `--prune-tags` may be able to be set with `GIT_FETCH_EXTRA_FLAGS` but I'm not sure if the flags are applied to clones or only fetch.

**Comment by cfxegbert** [comment]
Looking at the source
https://gitlab.com/gitlab-org/gitlab-runner/-/blob/main/shells/abstract.go#L535-540
https://gitlab.com/gitlab-org/gitlab-runner/-/blob/main/shells/abstract.go#L629-639

to replicate your setup would be:
```yaml
variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "0"
  GIT_FETCH_EXTRA_FLAGS: --prune-tags --prune --all --force
```
With the `clone` strategy since it removes the directory I don't think you need to prune.
