### ISSUE TITLE
PSR in a github action and uv.lock

### ISSUE THREAD

**Issue by aptly-io** [python-semantic-release/python-semantic-release#1097]
## Question
I've a github action `python-semantic-release/python-semantic-release@v9`. It updates the version in `pyproject.toml`, commits and tags this.

But now the `uv.lock` is no longer in sync: `uv lock` should have been called.

Is there a way that PSR can invoke additional commands to perform this and then also commit the updated `uv.lock` file?

Or should one create an additional github action step after the PSR process?

Someone has another suggestion?

Thanks!

### Configuration

The github action looks like
```yaml
      - name: Find version, stamp version, commit version, tag version
        uses: python-semantic-release/python-semantic-release@v9
        id: versioned
        with:
          changelog: false # no changelog generation (--no-changelog)
          vcs_release: false # no github release (--no-vcs-release)
          build: true
```
