### ISSUE TITLE
Changelog domain for self-hosted Gitlab

### ISSUE THREAD

**Issue by jdebetaz** [python-semantic-release/python-semantic-release#1128]
## Question

How can I change the domain url included in the changelog?

When I run `poetry run semantic-release --strict version`, I get https://gitlab.com instead of https://gitlab.my-domain.com as the link for each commit inside my changelog.

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
assets = []
build_command = "poetry build -n"
commit_message = "{version} [skip ci]\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"
version_toml = ["pyproject.toml:tool.poetry.version"]
version_variables = ["bmt_scripts/__init__.py:__version__"]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease = false
prerelease_token = "beta"

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = [
  "^Merge branch '.*'$",
  "^Merge pull request #.* from .*$",
]
template_dir = "templates"

[tool.semantic_release.changelog.environment]
autoescape = true
block_end_string = "%}"
block_start_string = "{%"
comment_end_string = "#}"
comment_start_string = "{#"
extensions = []
keep_trailing_newline = false
lstrip_blocks = false
newline_sequence = "\n"
trim_blocks = false
variable_end_string = "}}"
variable_start_string = "{{"

[tool.semantic_release.commit_author]
default = "semantic-release <semantic-release>"
env = "GIT_COMMIT_AUTHOR"

[tool.semantic_release.commit_parser_options]
allowed_tags = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "perf",
  "style",
  "refactor",
  "test",
  "merge",
]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote]
ignore_token_for_push = true
name = "origin"
type = "gitlab"

[tool.semantic_release.remote.token]
env = "CI_JOB_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
```

</details>
