### ISSUE TITLE
Custom changelog seems to ignore update mode

### ISSUE THREAD

**Issue by marc-at-brightnight** [python-semantic-release/python-semantic-release#1132]
## Question

How do I make sure the changelog entries operate in 'update' mode, even with a custom changelog? I noticed that the update mode was working perfectly until I switched to a custom template.

My end goal is simply to include the body of the commit in the changelog entry, hence why I have a custom template.

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
version_variables = ["__init__.py:__version__"]
upload_to_pypi = false
tag_format = "@[app]/[service]-v{version}"
commit_message = "chore(release): @[app]/[service]-v{version} [skip ci]"

[tool.semantic_release.changelog]
template_dir = "../../../documentation/templates"
mode = "update"

[tool.semantic_release.changelog.default_templates]
changelog_file = "../../../documentation/docs/[service]/changelog.md"

[tool.semantic_release.branches.test-semantic-release]
match = "test-semantic-release"
prerelease = false
```

</details>

## Additional context

my template (if there is an easier way to do this, please let me know):

```jinja
{# <root>/documentation/templates/documentation/docs/[service]/changelog.md.j2 #}

{% for version, release in ctx.history.released.items() %}
{{ "## %s (%s)" | format(version.as_semver_tag(), release.tagged_date.strftime("%Y-%m-%d")) }}
{% for type_, commits in (release.elements | dictsort) if type_ != "unknown" %}
{% set filtered_commits = [] %}
{% for commit in commits %}
{% if "[skip ci]" not in commit.message %}
{% set _ = filtered_commits.append(commit) %}
{% endif %}
{% endfor %}
{% if filtered_commits %}
{{ "### %s" | format(type_ | title) }}
{% for commit in commits %}
{{ "* %s ([`%s`](%s))" | format(
    commit.descriptions[0] | capitalize,
    commit.hexsha[:7],
    commit.hexsha | commit_hash_url
) }}
{% set lines = commit.message.split('\n') %}
{% set bullet_lines = [] %}
{% for line in lines[1:] %}
{% if line and (line.startswith('-') or line.startswith('*')) %}
{% set _ = bullet_lines.append(line) %}
{% endif %}
{% endfor %}
{% if bullet_lines %}
{% for bline in bullet_lines %}
    {{ bline }}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endfor %}
```

```yaml
# cicd.yml
# ... 
      - name: Create [service] github release
        if: needs.changes.outputs.[service] == 'true'
        uses: python-semantic-release/python-semantic-release@v9.15.2
        with:
          directory: poweralpha/services/[service]
          changelog: true
          commit: true
          push: true
          tag: true
          vcs_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          root_options: "-vv"
```
