### ISSUE TITLE
Add @ to allowed separators of version_variables

### ISSUE THREAD

**Issue by benedikt-hess-km** [python-semantic-release/python-semantic-release#1156]
### Description
Currently, when defining version variables with the `version_variables` configuration parameter, the versions in the specified files, have to be preceded by  `:`, `=` or `:=`.

See https://github.com/python-semantic-release/python-semantic-release/blob/2f18a6debfa6ef3afcc5611a3e09262998f2d4bf/src/semantic_release/cli/config.py#L719

I would like to add the `@` to the allowed separators, as it is used in gitHub actions ymls.

### Use cases
I have a github repo (e.g. `my-org/my-actions`) containing multiple actions:

```
my-actions/.github/workflows/
        action1.yml
        action2.yml
        combined.yml
```
`action1.yml` and `action2.yml` are both called by `combinded.yml`
```
on:
  workflow_call:
jobs:
  action1:
    uses: my-org/my-actions/.github/workflows/action1.yml@v1.2.3
  action2:
    uses: my-org/my-actions/.github/workflows/action2.yml@v1.2.3
```
Currently there is no way for PSR to update the two versions in the `combined.yml` file.

### Possible implementation
change line to `r"\s*(:=@|[:=])\s*",`
https://github.com/python-semantic-release/python-semantic-release/blob/2f18a6debfa6ef3afcc5611a3e09262998f2d4bf/src/semantic_release/cli/config.py#L719
