### ISSUE TITLE
Trying to enable parsing of squashed commits.

### ISSUE THREAD

**Issue by garrethcain** [python-semantic-release/python-semantic-release#1170]
## Question

I found the docs to be a little but unclear. It is mentioned that `You can toggle this feature on/off via the [commit_parser_options](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#config-commit-parser-options) setting.` But I can't find which setting it is.

### Configuration

Reading through the PSR changes, I came up with this;

```toml
[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test", "breaking"]
major_tags = ["breaking"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0
parse_squash_commits = true
```

Is the last line correct and in the correct place, do I need to make any other changes?

I'm using squash commits on BitBucket.
