### ISSUE TITLE
Add support for draft Github releases

### ISSUE THREAD

**Issue by rantoniuk** [python-semantic-release/python-semantic-release#1193]
### Description
GH supports `draft` releases (on the contrary to pre-releases) but I don't see any _draft_ reference on [GHA docs](https://python-semantic-release.readthedocs.io/en/stable/automatic-releases/github-actions.html#python-semantic-release-action).

Currently I have the following GH workflow:

```
      - name: Calculate version
        uses: python-semantic-release/python-semantic-release@v9.9.0
        id: semantic-release
        with:
          root_options: "-c .semantic-release.toml"
          github_token: ${{ steps.ghactions-auth.outputs.token }}
          push: "false"
          changelog: "false"
          vcs_release: "false"

      - name: Create GH release 
        uses: ncipollo/release-action@v1
        with:
          token: ${{ steps.ghactions-auth.outputs.token }}
          tag: ${{ steps.semantic-release.outputs.tag }}
          removeArtifacts: true
          generateReleaseNotes: true
          draft: true
          allowUpdates: true
          updateOnlyUnreleased: true

```

The above workflow runs only on feature (non-main) branches, determines the version and creates a draft GH release. If the release exists already, it is updated (i.e. the release notes are re-generated).

I'd like to move fully to `python-semantic-release` because it generates better decorated GH Release Notes.
