### ISSUE TITLE
Breaking change between 9.9.0 and 9.20.0

### ISSUE THREAD

**Issue by rantoniuk** [python-semantic-release/python-semantic-release#1194]
Config:

```
[semantic_release]
assets = []
commit_message = "{version}\n\nauto-version by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"
allow_zero_version = false

[semantic_release.branches.issue]
match = ".*"
prerelease = false
```

The following workflow works fine:

```
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.ghactions-auth.outputs.token }}
          fetch-depth: 0

      - name: Calculate version
        uses: python-semantic-release/python-semantic-release@v9.9.0
        id: semantic-release
        with:
          root_options: "-c .semantic-release.toml"
          push: "false"
          changelog: "false"
          vcs_release: "false"
```

but with `9.20.0` I'm getting the error:
```
Detached HEAD state cannot match any release groups; no release will be made
```

Was that intentional? (and should have been releases as ^10 instead?)

**Comment by codejedi365** [comment]
@rantoniuk, the only thing that I can point to is a change in `v9.8.5` that likely produced the error you see. 

The change was more of a bug fix as previously we did not isolate the difference between a detached head state and a non-matching release branch. This version needed to in order to provide the last release version information without failing because of a non-matching release.

In this situation I had to choose what to do with the different errors. A non-release branch will abort from evaluating or doing any semantic release actions but exit with a 0 exit code--unless in strict mode. 

A detached head state prevents PSR from evaluating a branch match completely which generally is a pre-requisite for using PSR. Which is why it was moved to the section that throws a non-zero exit code. 

Whether it was supposed to be breaking or not, is up for debate but ultimately doesn't matter as I can't do anything about it now as this was over 8 months ago. 

The fact you were in a detached head state (the default for many CI envs) is problematic as nothing should of released with it (even the default branch) which is why it should be a nonzero exit code in the first place.

**Comment by rantoniuk** [comment]
Thanks for the detailed explanation, I fully understand it. One thing to point out though:

> The fact you were in a detached head state (the default for many CI envs) is problematic as nothing could of released with it (even the default branch) which is why it should be a nonzero exit code in the first place.

PSR could be used for generating the version number only (and in `noop` mode) and it worked correctly on a detached state. I'm curious also how did this work for everyone until 9.8.5? 

I see the `Setup | Force` step in the docs, wouldn't `ref: ${{ github.ref_name }}` work?

Feel free to close if there's nothing to do here though :)

**Comment by codejedi365** [comment]
> PSR could be used for generating the version number only (and in `noop` mode) and it worked correctly on a detached state. I'm curious also how did this work for everyone until 9.8.5? 

Yes, I'm aware of using it to determine a version number but it still would have failed in a detached head state. I don't know how it worked for you before but that was a long time ago to remember the nuances. The no-op mode doesn't change the fact that this decision to abort is during the configuration loading. 

> I see the `Setup | Force` step in the docs, wouldn't `ref: ${{ github.ref_name }}` work?

At face value it looks like it would but the problem arises when to PRs or pushes happen in succession before the previous pipeline has succeeded in release. If you just check out the main branch directly it could have moved forward and then you would be accidentally releasing something that was not tested. This actually happened to PSR, luckily it wasn't broken. This is why the recommendation is to checkout the workflow sha (the tested state) and then force the branch to be at the location you tested. This is why there is a comment in the docs example.

**Comment by skwde** [comment]
Hopefully it helps others that find this issue before a solution (when using Gitlab CI/CD

Here is the essential part of the release stage in `.gitlab-ci.yml` that finally worked for me

```yml
release:
  <...>
  before_script:
    <...>
    - git checkout $CI_COMMIT_BRANCH
    - git reset --hard $CI_COMMIT_SHA
  script:
    - semantic-release version && semantic-release publish
  variables:
    <...>
    GIT_DEPTH: 0
    GIT_STRATEGY: clone
```

Maybe somehting like this should be added to the docs under a dedicated section Gitlab CI/CD.
