### ISSUE TITLE
404 in API call to xxx/releases

### ISSUE THREAD

**Issue by dimaqq** [python-semantic-release/python-semantic-release#1197]
### Description

My entire CI:
```yaml
on:
  push:
    branches: [main]

jobs:
  test-psr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - run: uvx --from python-semantic-release psr -v -v -v version
```

### Expected behavior

Bump a version, update changelog, tag the branch

### Actual behavior

```
404 Client Error: Not Found version.py:777
                    for url:                                                    
                    https://api.github.com/repos/dimaqq/otlp-test               
                    -data/releases                                              
                    NoneType: None                                              
404 Client Error: Not Found for url: https://api.github.com/repos/dimaqq/otlp-test-data/releases
```

### Environment

-  **Operating System (w/ version):** 
-  **Python version:** 
-  **Pip version:** 
-  **Semantic-release version:** 
-  **Build tool (w/ version):** 

<details>
<summary><code>pip freeze</code></summary>

```log

```

</details>

<br>

<details>
<summary><code>git log --oneline --decorate --graph --all -n 50</code></summary>

```log

```

</details>

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
```

</details>
<br>

<details>
<summary>Build System Configuration</summary>

```toml
```

</details>
<br>

<details>
<summary>GitHub Actions Job Definition</summary>

```yaml

```

</details>

### Execution Log

<details>
<summary><code>semantic-release -vv <i>command</i></code></summary>

```log

```

</details>

**Comment by codejedi365** [comment]
Need you to fill out the template.

**Comment by dimaqq** [comment]
job logs: https://gist.github.com/dimaqq/4890b5466b5fd8e5c53fbe017f330142

github.com runner

pyproject.toml
```toml
[tool.semantic_release]
version_variables = ["pyproject.toml:project.version"]
tag_format = "{version}"

[tool.semantic_release.changelog]
changelog_file = "changelog.md"
exclude_commit_patterns = ["ci", "test", "chore(deps)"]
mode = "update"
```
