### ISSUE TITLE
semantic-release won't release new version (has already been released) / repository in broken state

### ISSUE THREAD

**Issue by Sieboldianus** [python-semantic-release/python-semantic-release#1206]
## Question
I have used python-semantic-release for a while and it worked always pretty well. Since a few commits, it won't release a new release because "v0.25.0 has already been released". And I don't understand why.

### Configuration

I manually issue new releases once in a while, locally, with
```
semantic-release -vv version
semantic-release -vv publish
```

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
assets = []
version_variables = [
    ".version:__version__",]
commit_version_number = "true"
branch = "master-latest"

[tool.semantic_release.branches.main]
match = "(master-latest)"

[tool.semantic_release.remote]
name = "origin"
type = "gitlab"
ignore_token_for_push = false
domain = "gitlab.....de"
api_domain = "gitlab.....de/api/v4"

[tool.semantic_release.remote.token]
env = "GL_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = []
upload_to_vcs_release = false
build_command = false
```

</details>

<details>
<summary><code>git log --oneline --decorate --graph --all -n 50</code></summary>

```log
* ef05e1f (HEAD -> master-latest, origin/master-latest) fix: CARTOLAB_VERSION not available on runtime
* 16b6780 feat: start terminal sessions in bash by default
* f263464 feat: add carto-lab docker version to browser tab
* 8b06d4b feat: add 7zip for packaging
* 0d7a8fd feat: add Cookiecutter env for reproduction package workflow
* c73ba62 Update jupyterlab test to 4.4.0b0
* 7afd62c refactor: remove Mapnik fonts bind in r-compose
* dbe557a perf: reduce build size of Mapntik image
* 37769ae refactor: use version from TAG in build process
* 2da30e2 ci: reduce build complexity by relying on TAG instead of extra APP_VERSION
* 32e108b Improve colors of inverse
* 235dc06 Add inverse colors logo
* e519bd5 style: new logo
* 2f97f88 docs: update Matrix for v0.25.0
* a37e010 0.25.0 **<--- this?**
* 91283ae feat: pin jupyterlab 4.4.0a3 and latest (beta) RTC package
* fc18033 fix: dask not compatible with latest Bokeh
* 821a45f feat: allow RTC, collaboration and git-extension to be enabled alongside each other
* 42592db docs: update versions for 0.13.0
* 3263d6f docs: add compatibility matrix for version 0.19.0
| * 50589a8 (tag: v0.25.0) 0.25.0 **<--- this**
| * ddf229c feat: pin jupyterlab 4.4.0a3 and latest (beta) RTC package
| * 177dc0a fix: dask not compatible with latest Bokeh
| * c15e96c feat: allow RTC, collaboration and git-extension to be enabled alongside each other
|/
* da49a27 tests: add get_versions.sh as version check & package integration test
* 31ba544 Fix typo
* 20e3aa7 docs: add compatibility matrix
* b9a88a9 Revise collaboration section
* dffb652 Remove space
* 544130c minor rephrase
* 4b435a5 Clarify collaborative mode in docs
* 481fe0e Cleanup mermaid graphs
* 66064f6 ci: enable mermaid plugin
* 6781695 Fix indent
* f5f9ea9 docs: improve description of collaboration mode and jupytext incompatibility
* 9db3c60 ci: use explicit mkdocs registry version tag; add mermaid
* 73be50d 0.24.2
* ff4cbdb fix: disable jupyter real time collaboration (RTC) extension by default
* a711178 docs: clarify difference between COLLABORATIVE and DISABLE_JUPYTER-COLLABORATION flags
| * 68eb33a (tag: v0.24.2) 0.24.2
| * 3a089ef fix: disable jupyter real time collaboration (RTC) extension by default
|/

```

```
> git tag
v0.20.0
v0.21.0
v0.22.0
v0.22.1
v0.22.2
v0.23.0
v0.23.1
v0.23.2
v0.24.0
v0.24.1
v0.24.2
v0.25.0
```

</details>
