### ISSUE TITLE
Version files left unstaged for commit in 2 stage PSR execution

### ISSUE THREAD

**Issue by codejedi365** [python-semantic-release/python-semantic-release#1211]
## Bug Report

Separated into its own issue from #1125, comments from @JonZeolla

### Description

In order to resolve #1125, I implemented your two step workflow documented in https://github.com/python-semantic-release/python-semantic-release/issues/1125#issuecomment-2545857234. And unfortunately it seems with v9.20.0, the 2 step workflow does not commit the `version_variables` and `version_toml` changes unless I intentionally stage them myself.

### Expected behavior

The `version_variables` and `version_toml` configured files are committed with the release commit while also allowing me to keep uv.lock updated in between the steps.

### Actual behavior

The version files were not committed in the release commit while the `uv.lock` was. The version files remained in the working directory

### Environment

-  **Operating System (w/ version):** 
-  **Python version:** 
-  **Semantic-release version:** v9.20.0

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
major_on_zero = false
version_toml = [
    "pyproject.toml:project.version",
]
version_variables = [
    "src/example/__init__.py:__version__",
]
changelog_file = "CHANGELOG.md"
commit_parser = "angular"
commit_author = "Example <Example@example.com>"
commit_message = "chore(release): example {version}"
tag_format = "example=={version}"

[tool.semantic_release.branches.release]
match = "main"

[tool.semantic_release.publish]
dist_glob_patterns = ["path_relative_to_root/example/dist/*"]
upload_to_vcs_release = true

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false
```

</details>

### Execution Log

<details>
<summary><code>semantic-release -vv <i>version</i></code></summary>

```log

```

</details>

### Additional context

My guess is that it's [this](https://github.com/python-semantic-release/python-semantic-release/commit/8906d8e70467af1489d797ec8cb09b1f95e5d409#diff-266604af13373648efa1dfeca568745d31ae9dc9dea99d375ef448213d18c043R166-R173) and [this](https://github.com/python-semantic-release/python-semantic-release/commit/8906d8e70467af1489d797ec8cb09b1f95e5d409#diff-beff84abd8e06585ac477cc2dea162260da0f081e113b45e84fcb8de13c031a7R107-R114). Since we stage the changes before running the `--commit`, the `new_content` is the same as `self.content` (in the working tree), so it returns `None`.

Then, that doesn't add the file path to `paths` [here](https://github.com/python-semantic-release/python-semantic-release/commit/8906d8e70467af1489d797ec8cb09b1f95e5d409#diff-05d92313677c9daccff22980a710577b49b61ee7b62c189844527e8ce95965b3R148-R161), which means it is not added to `files_with_new_version_written` here:

https://github.com/python-semantic-release/python-semantic-release/blob/5093f30da0746a9a5302fb37c62d6aae028a930c/src/semantic_release/cli/commands/version.py#L617-L623

And then finally, it isn't staged and commit here:

https://github.com/python-semantic-release/python-semantic-release/blob/5093f30da0746a9a5302fb37c62d6aae028a930c/src/semantic_release/cli/commands/version.py#L654-L668
