### ISSUE TITLE
How to replace version in README.md

### ISSUE THREAD

**Issue by glema-xmartlabs** [python-semantic-release/python-semantic-release#1218]
### Description
I want to parse the version that is in my README.md file
```
Current version: v1.0.0
```

### Expected behavior
After a minor fix, I expect README.md file to look like this:
```
Current version: v1.0.1
```

### Actual behavior
```
Current version: v1.0.0
```

Version in pyproject.toml gets updated correctly

### Environment

-  **Python version:** - 3.10.14
-  **Semantic-release version:** 9.21.0
-  **Build tool (w/ version):** uvx 0.6.5 

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
tag_format = "v{version}"
version_pattern = [
    "README.md:Current version: v{version}",
]
version_toml = [
    "pyproject.toml:project.version"
]
```

</details>
<br>
