### ISSUE TITLE
How to revert a release

### ISSUE THREAD

**Issue by iseppe** [python-semantic-release/python-semantic-release#1223]
## Question
I was testing this tool and ran:

`semantic-release version --no-vcs-release`

As expected, it:
- Bumped the version from `1.9.0` to `1.9.1`
- Updated `CHANGELOG.md`
- Created a `v1.9.1` tag on my remote

After confirming the setup was working, I wanted to revert the version bump and remove the `v1.9.1` tag. I changed back (without using `git revert` or `git reset`) the version to `1.9.0` and deleted the tag from the remote.

However, when I made another commit, `semantic-release` bumped the version to `1.9.2` instead of `1.9.1`.

What's the best way to properly revert one or more releases in this scenario?

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
no_git_verify = false
tag_format = "v{version}"
version_variables = [
    # "file:variable:format_type"
    "__init__.py:__version__",
]

[tool.semantic_release.branches.main]
match = "(main|master|dev)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
mode = "update"
insertion_flag = "<!-- version list -->"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
other_allowed_tags = ["build", "chore", "ci", "docs", "style", "refactor", "test"]
allowed_tags = ["feat", "fix", "perf", "build", "chore", "ci", "docs", "style", "refactor", "test"]
default_bump_level = 0
parse_squash_commits = false
ignore_merge_commits = false

[tool.semantic_release.remote]
name = "origin"
type = "gitlab"
ignore_token_for_push = false
insecure = false
token = { env = "GITLAB_TOKEN" }
```

</details>

## Additional context

<details>
<summary><code>git log --oneline --decorate --graph --all -n 50</code></summary>

```log
* d2a4b54 (HEAD -> dev, tag: v1.9.3, origin/dev) 1.9.3
* 4bafbf5 fix: typo preventing crons from scheduling correctly
* 419df0a Update file __init__.py
* db5b4f5 1.9.2
* 7d6527f chore(semver): add insertion_flag
* 9362f7f fix: revert version
* 7aa017a 1.9.1
* acaa67d fix: remove test file
* 9741226 test: test cicd configuration
*   802ec04 Merge branch 'dev' of https://example.com/project into dev
|\  
| * 37b3416 ci: update .gitlab-ci.yml file
* | 388d454 ci: update semantic-release integration
|/  
*   e3b5d53 Merge branch 'dev' of https://example.com/project into dev
|\  
| * c7d7149 (tag: v1.9.0) 1.9.0
* | e2dc169 ci: update config
|/  
*   e70afd4 feat: automatic semantic versioning
```

</details>

<details>
<summary><code>.gitlab-ci.yml (semver stage)</code></summary>

```yaml

stages:
  - pre-build
 
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /^(feat|fix|perf|build|chore|ci|docs|style|refactor|test)(\(.*\))?:/
      when: always

semantic-release:
  stage: pre-build
  tags:
    - local
  script:
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.com"
    - git fetch --unshallow origin || git fetch origin
    - git fetch --tags origin
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH
    - python3 -m venv venv
    - source venv/bin/activate
    - python3 -m pip install python-semantic-release
    - semantic-release version --no-vcs-release 2>/dev/null
    - semantic-release version --print 2>/dev/null > .current_version
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "10 mins"
    paths:
      - .current_version
```
</details>

**Comment by codejedi365** [comment]
@iseppe, first I want to thank you for filling out the entire issue template! I know this seems weird but lately people have been super lazy in filling it out and so I'm unable to respond or debug effectively in a timely manner.

So the issue lies with the default method in which GitLab instantiates your repository for each job.  The default is to use the fetch git strategy and checkout a detached head with a fetch depth of 50.  This is fine and relatively quick for most jobs except pretty much all not good for a PSR environment. As I have provided my recommended workflow in this https://github.com/python-semantic-release/python-semantic-release/issues/1046#issuecomment-2387800177, you will see a few special bash commands which solve these issues.

You have done the first part which is unshallow the repo. You have also checked out the proper branch, however I would use the `-B` option because if the branch happened to move in the course of the workflow executing you will release code that you didn't test (happens when 2 PRs are merged before a single workflow finishes).  The trap you fell into is related to the git strategy for building the project directory--the fetch strategy.  I personally think this is a flaw of GitLab and should be changed but I haven't gotten around to a PR for it.  

My solution is that you need to run the command that GitLab should of ran which is:

```sh
# --prune-tags elminates the cached tags that were no longer on the remote 
# (ie the one you deleted but still existed in the cached build repository from the previous job execution)
# --prune removes any deleted branches
# --force will make sure any tags that have moved are corrected to mirror the remote
git fetch --prune-tags --prune --all --force

# you can combine the unfetch with the above command for
git fetch --unshallow --prune-tags --prune --all --force
```

Unfortunately if it is at the beginning of a project and you don't have more than 50 commits you will get an error with the `--unshallow` option (the last time I checked). So that means you have to wrap the unshallow command in an `if`, which results in a command like this:

```sh
if git rev-parse --is-shallow-repository | grep -q "true"; then
    git fetch --unshallow --prune-tags --prune --all --force;
else
    git fetch --prune-tags --prune --all --force;
fi
```

Gross, right? That is why I wish GitLab would have changed their default fetch strategy to include the `--prune-tags`.

### However 

Thanks to @cfxegbert, he illuminated a much easier way to do the same thing via special `GIT_` environment vars that will change the GitLab behavior.  We change the `GIT_STRATEGY` to `clone` eliminates the silly disparity between local and remote.  We also define the fetch depth via `GIT_DEPTH=0` and it unshallows for us. Set the variables like this:

```yaml
release:
  stage: release
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"
```

I have been working on a GitLab guide (to solve #666) but I got sick this week. This is my latest **untested** example to include the newer git environment variable solution:

```yaml
release:
  stage: release
  rules:
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH'
      when: manual       # <--- leave this out if you want auto-publish
  allow_failure: false      # must have when it is set to manual otherwise GitLab will move on to publish
  resource_group: release-$CI_COMMIT_BRANCH
  environment:
    name: repository       # custom environment that holds the PAT (and only available to this job)
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"
  script:
    # Git checkout always creates a detached HEAD at CI_COMMIT_SHA
    # Force checkout of the active branch at the current commit sha (prevents accidental movement of branch)
    - git checkout -B "$CI_COMMIT_BRANCH" HEAD
    
    # set the remote url to the PAT (write repository access)
    # NOT NECESSARY IF YOU ARE ON A SELF-HOSTED GITLAB 17.2+ with the feature flag for CI_JOB_TOKEN enabled
    - git remote set-url origin "https://__token__:$GITLAB_TOKEN@${CI_REPOSITORY_URL#*@}"
    
    # Last chance to abort before causing an error as another PR/Push was applied to the upstream
    # branch while this pipeline was running.  This is important because we are committing a version
    # change (--commit).  You may omit this step if you are using --no-commit.
    - bash .gitlab/ci/verify_upstream.sh

    # This provides an exit code of whether or not to release, on exitcode 0 it runs the release,
    # on non-zero it writes a status to a file that is passed on to the next job as an environment variable
    - if semantic-release -vv --strict version --print; then
         semantic-release version;
         printf '%s\n' "PSR_RELEASED=true" >> publish.env;
         printf '%s\n' "PSR_RELEASED_VERSION=$(semantic-release version --print-last-released 2>/dev/null)" >> publish.env;
      else
         printf '%s\n' "PSR_RELEASED=false" >> publish.env;
      fi
  after_script:
    # reset the remote url to the CI token (read repository access)
    - git remote set-url origin "$CI_REPOSITORY_URL"
  artifacts:
    reports:
      dotenv: publish.env
```

Note, I also included the `resource_group` directive which ensures that only one release job executes at a time.

Note another new thing is my use of a `verify_upstream` script.  That is important to prevent a version commit onto your branch when it might have moved from another PR merge.  Add the following to your repository to prevent this circumstance if you are using the `--commit` option (the default).

```sh
#!/bin/bash
# FILE: .gitlab/ci/verify_upstream.sh

set -eu +o pipefail

# Example output of `git status -sb`:
#   ## master...origin/master [behind 1]
#   M .github/workflows/verify_upstream.sh
UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"

set -o pipefail

if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
    printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
    exit 1
fi

git fetch "${UPSTREAM_BRANCH_NAME%%/*}"

if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
    printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
    exit 1
fi

HEAD_SHA="$(git rev-parse HEAD)"

if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
    printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
    printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
    exit 1
fi

printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
```

Maybe one day this will be incorporated into PSR but it its a little outside of the scope of PSR and rather a defensive CI environment prevention technique.

**Comment by codejedi365** [comment]
Oh and if you are wondering where my git setup commands are that you are using, I use a hidden job that has the `before_script` directive defined for git setup and python installation. I then use this hidden job as a template for all jobs and use the `extends` directive to only write those commands once.

**Comment by iseppe** [comment]
@codejedi365 
Thank you very much for your detailed response. I will try this configuration and see if this works for my use case.

P.S: I know what it means to read and trying to understand a half baked issue and I try my best to include every details that might be useful.

**Comment by iseppe** [comment]
> Oh and if you are wondering where my git setup commands are that you are using, I use a hidden job that has the `before_script` directive defined for git setup and python installation. I then use this hidden job as a template for all jobs and use the `extends` directive to only write those commands once.

Btw, could you please expand more on the configuration of your `before_script` hidden job?

I'd like to try and keep things as clean as possible

@codejedi365

**Comment by codejedi365** [comment]
> > Oh and if you are wondering where my git setup commands are that you are using, I use a hidden job that has the `before_script` directive defined for git setup and python installation. I then use this hidden job as a template for all jobs and use the `extends` directive to only write those commands once.
> 
> Btw, could you please expand more on the configuration of your `before_script` hidden job?

Sure, its documented here on [GitLab CI/CD](https://docs.gitlab.com/ci/yaml/#extends).  A hidden job is defined as any job that starts with a period (`.`). This concept matches the Linux concept of hidden folders or files.  A hidden job can be an incomplete/partial job definition (i.e. does not have to have a `script` or `stage` derivative) because is not executed by default. Then you define your normal job and use the `extends` directive to inherit all the settings of the previous job. Any new directives include will directly override the keys of the inherited job.  **IT WILL NOT MERGE LISTS.** If you want to define list items once and then add a few more to them you must use yaml anchors to do so.  

Because of the override concept, it is a smart strategy to place all your setup commands into a hidden job under the `before_script` key and then in your main job just define the `script` key.  This way your setup instructions are not overridden and each subsequent job is more condensed to only the differences.  Note that the `before_script` and the `script` directives are executed in the same common shell environment **BUT** this is not true for the `after_script` directive.  The `after_script` directive is run in a new shell environment because in theory it is a clean up step that runs regardless if the `before_script` or `script` commands exited with a non-zero exit code.  The nice part about the `before_script` and `script` commands using the same shell is that the activation of the python virtual environment is inherited from the `before_script` to the `script` commands.

This is what I do:

```yaml
.dev-setup:
  image: python:3.10-bookworm
  cache:
    - &pip-cache                   # <--- this is a yaml anchor (naming a ref to be de-referenced later)
      key:
        files:
          - pyproject.toml
      paths:
        - $VIRTUAL_ENV
      policy: pull
  before_script:
    # Enable local git operations (commit & tag)
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.com"
    - python3 -m venv "$VIRTUAL_ENV"
    - source "$VIRTUAL_ENV/bin/activate"
    - pip install --upgrade pip setuptools wheel
    - pip install -e .[build,dev,test]
    # Helpful for debugging
    - python3 --version
    - pip list
  tags:
    - gitlab-org


build:
  stage: check
  extends: .dev-setup
  script:
    - bash ./.gitlab/ci/build.sh
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 week


# You can also do double inheritance, like for testing across multiple versions of python
.test-base:
  stage: test
  extends: .dev-setup
  needs:
    - job: build
      artifacts: true
  script:
    # remove the editable install
    - pip uninstall -y "$CANONICAL_PKG_NAME"
    # install our distribution package for testing
    - pip install dist/*.whl
    # Verify our [project.script] is available on the path
    - $CONSOLE_SCRIPT_NAME --help
    - $CONSOLE_SCRIPT_NAME --version
    # Glob resolve the location of the installed package source code
    - DISTRIBUTION_SRC="$(eval "realpath .venv/lib/python3*/site-packages/$REAL_PKG_NAME")" &&
        echo "DISTRIBUTION_SRC=$DISTRIBUTION_SRC"
    # run the tests (with as many cores available)
    - pytest -nauto
        --junitxml=test-results.xml
        --cov="$DISTRIBUTION_SRC"
        --cov-context=test
        --cov-report=term-missing:skip-covered
        --cov-report=xml
        --cov-fail-under=60
  artifacts:
    when: always
    reports:
      junit: test-results.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
    expire_in: 1 week


test-py3.11:
  extends: .test-base
  image: python:3.11-bookworm


test-py3.12:
  extends: .test-base
  image: python:3.12-bookworm
```
