### ISSUE TITLE
How to make semantic release respect pyproject.toml project.version?

### ISSUE THREAD

**Issue by Kugeleis** [python-semantic-release/python-semantic-release#1227]
I have a pyproject.toml with:

```toml
[project]
name = "my-great-project"
version = "0.3.2"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",
]
```
but python semantic release does not read this version. If I try it with `semantic-release --noop version` it want to make a version v0.0.1. How to ensure it respects the project version entry?
