### ISSUE TITLE
Custom CHANGELOG template not being applied with python-semantic-release v7.34.6

### ISSUE THREAD

**Issue by cy0926** [python-semantic-release/python-semantic-release#1230]
### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
changelog_template = "templates/CHANGELOG.md.j2"
version_variable = "pyproject.toml:tool.poetry.version"
version_source = "tag"
commit_version_number = true  # enable `commit version number` to make semantic release commit changed files
upload_to_repository = false
build_command = false  # Default: python setup.py sdist bdist_wheel
hvcs = "gitlab"
```
**templates/CHANGELOG.md.j2:** 
```
# {{ version }}

{% for type in ['feat', 'fix', 'chore', 'docs', 'style', 'refactor', 'test', 'ci', 'perf', 'build', 'revert'] %}
  {% if changelog[type] %}
## {{ type|capitalize }}

  {% for commit in changelog[type] %}
- {{ commit.message.split(':')[0] }}{% if commit.scope %}({{ commit.scope }}){% endif %}
  [View Commit]({{ commit.url }})
  ​**​Author​**​: {{ commit.author.name }}
  {% endfor %}
  {% endif %}
{% endfor %}
```
**Project Structure：**
```
my-project/
├── templates/
│   └── CHANGELOG.md.j2
├── pyproject.toml
└── tests/
```

</details>

## Additional context

I'm using python-semantic-release (version 7.34.6, do not consider upgrading) in a Python project with poetry as the package manager. I attempted to customize the generated CHANGELOG by creating a custom. However, the generated CHANGELOG.md still uses the default template instead of my custom one.

Please help me point out where the configuration is wrong. I hope that the changlog.md file can be generated according to the customized template in the end.
