### ISSUE TITLE
bug: No-op mode fails to log any bracket-encased text in commit_message

### ISSUE THREAD

**Issue by andreub** [python-semantic-release/python-semantic-release#1251]
### Description

when using the following configuration
```
[tool.semantic_release]
version_variables = [ "VERSION:__version__" ]
upload_to_pypi = false
commit_message = "{version}\n\nVersion generated by python-semantic-release [ci skip]"
```
`"[ci skip]"` is ignored:

### Expected behavior

The whole provided commit_message should be included in the commit message
```
[🛡 NOP]         would have run:
                            GIT_AUTHOR_NAME=semantic-release \
    GIT_AUTHOR_EMAIL=semantic-release \
    GIT_COMMITTER_NAME=semantic-release \
    GIT_COMMITTER_EMAIL=semantic-release \
    git commit -m '6.237.5

            Version generated by python-semantic-release [ci skip]'
```

### Actual behavior
```
[🛡 NOP]         would have run:
                            GIT_AUTHOR_NAME=semantic-release \
    GIT_AUTHOR_EMAIL=semantic-release \
    GIT_COMMITTER_NAME=semantic-release \
    GIT_COMMITTER_EMAIL=semantic-release \
    git commit -m '6.237.5

            Version generated by python-semantic-release '
```

### Environment

-  **Operating System (w/ version):**MacOS Darwin 24.5.0 Darwin Kernel Version 24.5.0: RELEASE_ARM64_T8112 arm64 arm Darwin
-  **Python version:** 3.11.4
-  **Pip version:** 23.1.2
-  **Semantic-release version:** 9.21.1
-  **Build tool (w/ version):** None

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
version_variables = [ "VERSION:__version__" ]
upload_to_pypi = false
commit_message = "{version}\n\nVersion generated by python-semantic-release [ci skip]"
commit_parser = "conventional"
```

</details>
