### ISSUE TITLE
What am I missing with bitbucket configuration?

### ISSUE THREAD

**Issue by andriibutko** [python-semantic-release/python-semantic-release#1277]
## Question
I've set up semantic-release for our project, and it works well; however, the links generated for each commit in the changelog are broken because they are pointing to `github.com` instead of `bitbucket.org`.

It looks like I'm missing something, but I have no idea what. I set the BITBUCKET_REPO_FULL_NAME env variable; however, it also isn't working. 

I really appreciate any help you can provide.

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.branches."feature/testing-semantic"]
match = "feature/testing-semantic"
prerelease_token = "rc"
prerelease = true

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md" # Markdown format

[tool.semantic_release.changelog]
insertion_flag = "<!-- version list -->"
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+'''
]

[semantic_release.remote]
type = "bitbucket"
ignore_token_for_push = true
insecure = true
domain = "bitbucket.org"
```

</details>

## Additional context

It looks like I'm doing something wrong with the environment variables, cause the token that I've created for Bitbucket is also not recognized, and whenever I run the changelog generation, I get:

```
semantic-release changelog                      
[08:32:16] WARNING  Token value is missing!
```
Env variables are being exported before the command execution. For the token I used: 
```
export BITBUCKET_TOKEN="token"
```
