### ISSUE TITLE
Build_command not found in path

### ISSUE THREAD

**Issue by alandtse** [python-semantic-release/python-semantic-release#222]
## The problem

The build_command not found in path for GitHub Actions

## Expected behavior

The build_command command runs successfully.

## Additional context

```
[semantic_release]
version_variable=pyproject.toml:version
upload_to_pypi=true
check_build_status=false
remove_dist=false
hvcs=gitlab
build_command="poetry publish --build"
```

```
 $ pip install poetry
<snip>
 $ poetry config virtualenvs.create false
 $ poetry install
<snip>
 $ pip install python-semantic-release
<snip>
 $ semantic-release publish
 Creating new version
 Current version: 1.6.1
 Bumping with a minor version to 1.7.0
 Pushing new version
 Building distributions
 Running "poetry publish --build"
 /bin/bash: poetry publish --build: command not found
 error: Encountered a bad command exit code!
 error: 
 error: Command: '"poetry publish --build"'
 error: 
 error: Exit code: 127
 error: 
 error: Stdout: already printed
 error: 
 error: Stderr: already printed
 error: 
```

**Comment by alandtse** [comment]
I'm not too familiar with the [`run` command from invoke ](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/dist.py#L15)and whether there are any gotchas to get the right path so I'm hoping someone else knows the right way to fix it.

**Comment by alandtse** [comment]
Changing the build_command to `$HOME/.poetry/bin/poetry` may be the workaround per https://github.com/python-poetry/poetry/issues/525

**Comment by browniebroke** [comment]
I recently migrated a project which was using PSR on Github actions to Poetry and here is [the config I'm using](https://github.com/browniebroke/deezer-python/blob/ccdf30cdb2efea9c144f34b220ec0495b5a46824/pyproject.toml#L62-L68):


```toml
[tool.semantic_release]
version_variable = [
    "deezer/__init__.py:__version__",
    "pyproject.toml:version"
]
build_command = "pip install poetry && poetry build"
```

This works because a couple of things work nicely together:

- The `version_variable` can be specified [in multiple places](https://python-semantic-release.readthedocs.io/en/latest/configuration.html?highlight=version_source#version-variable), once in `pyproject.toml` and once in the module `__init__.py`
- The version replacement works in TOML file because the format [is the same as it would be in Python](https://github.com/relekang/python-semantic-release/blob/71fdb9ff83e56b22367dd810b09e2eaec51c6155/semantic_release/history/__init__.py#L48): `version = "1.2.3"`
- Multiple commands are passed to the `build_command` with `&&`. The documentation [uses `flit` as an example](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#build-command), but it works the same for Poetry.
- Poetry builds the source and binary distributions in a standard location `dist/` by default, which [is perfectly compatible](https://github.com/relekang/python-semantic-release/blob/71fdb9ff83e56b22367dd810b09e2eaec51c6155/semantic_release/pypi.py#L17) with what [PSR uses to publish (Twine)](https://github.com/relekang/python-semantic-release/blob/71fdb9ff83e56b22367dd810b09e2eaec51c6155/semantic_release/pypi.py#L48)

Hope this helps!

**Comment by schlich** [comment]
Been running into this issue with the GitHub Action in CI. the `"pip install poetry && poetry build"` seems ok as a workaround, but this configuration will unnecessarily re-install Poetry if running semantic-release locally.  there is no way to my knowledge to give third-party actions access to your job's runner, so in the meantime i've resorted to just manually calling semantic-release on the GitHub runner created by the workflow/job:

```
    - name: Semantic Release
      run: |
        poetry run semantic-release version
        poetry run semantic-release publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
```

I figure that configuring the action to use Poetry shouldn't be any more difficult than adding an installation command to the Dockefile.  I can put together a PR if this is acceptable.

**Comment by chriscarrollsmith** [comment]
I am running into this with `uv`. According to docs, PATH is supposed to be passed automatically to the build env. But for whatever reason, it seems not to find `uv` on the PATH.

**Comment by codejedi365** [comment]
> I am running into this with `uv`. According to docs, PATH is supposed to be passed automatically to the build env. But for whatever reason, it seems not to find `uv` on the PATH.

I'm going to guess you are using the GitHub action? If so you need to see browniebroke's solution above with including the pip install command of `uv` in the `build_command`. This is because the GitHub Action is a container action and does not inherit the entire environment.

**Comment by chriscarrollsmith** [comment]
> > I am running into this with `uv`. According to docs, PATH is supposed to be passed automatically to the build env. But for whatever reason, it seems not to find `uv` on the PATH.
> 
> [@chriscarrollsmith](https://github.com/chriscarrollsmith), I'm going to guess you are using the GitHub action? If so you need to see browniebroke's solution above with including the pip install command of `uv` in the `build_command`. This is because the GitHub Action is a container action and does not inherit the entire environment. This limitation is described at the bottom of the first paragraph in the [docs](https://python-semantic-release.readthedocs.io/en/stable/automatic-releases/github-actions.html#python-semantic-release-action)

ahhh, that clarifies things; thanks

**Comment by aqib-bhat** [comment]
@browniebroke @alandtse Thank you for your input on this issue! I was able to make it work with `uv` as follows:

```toml
[tool.semantic_release]
version_variables = ["pyproject.toml:version"]
build_command = "curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env && uv build"
```

Link: https://github.com/aqib-oss/sonar-qube-gh-action/blob/main/pyproject.toml
