### ISSUE TITLE
failing to recognize the current version and always cutting a major release

### ISSUE THREAD

**Issue by esatterwhite** [python-semantic-release/python-semantic-release#387]
## The problem

Semantic release is failing to recognize the current version and always cutting a major release

* python-semantic-release 7.19.2

## Expected behavior

Should recognize that the tag exists and apply the appropriate version

## Additional context

Output log 
```
[2021-09-27T20:13:21.771Z] debug: get_current_version_by_config_file()
[2021-09-27T20:13:21.771Z] debug: Parsing current version: path=PosixPath('kong_bench/__init__.py') pattern='__version__ *[:=] *["\\\'](\\d+\\.\\d+(?:\\.\\d+)?)["\\\']' num_matches=1
[2021-09-27T20:13:21.771Z] debug: Regex matched version: 13.0.0
[2021-09-27T20:13:21.771Z] debug: get_current_version_by_config_file -> 13.0.0
[2021-09-27T20:13:21.771Z] debug: evaluate_version_bump('13.0.0', None)
[2021-09-27T20:13:21.771Z] debug: Reference v13.0.0 does not exist, considering entire history
[2021-09-27T20:13:21.771Z] debug: parse_commit_message('fix(ci): A fix a version variable for semantic-release
[2021-09-27T20:13:21.771Z] debug: 
[2021-09-27T20:13:21.771Z] debug: adds the version variable parameter to the main module init file
```

Remote tags
```bash
git tag

v1.0.0
v10.0.0
v11.0.0
v12.0.0
v13.0.0
v2.0.0
v3.0.0
v4.0.0
v5.0.0
v6.0.0
v6.0.1
v7.0.0
v8.0.0
v9.0.0
```

release config

```toml
[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = "kong_bench/__init__.py:__version__"
branch = "main"
build_command = "poetry build"
upload_to_pypi = false
dist_path = "dist"
commit_subject = "release: Version {version} [skip ci]"
commit_author = "LogDNA Bot <bot@logdna.com>"
```

**Comment by jacksbox** [comment]
same problem here... I always get majot bumps, wit just chores and refactors in the history

**Comment by esatterwhite** [comment]
I think the problem is the reliance on the local repository and how it is assumed to have been created. If it isn't a full clone, this will generally happen. 

The reference JS implementation queries the remote for tags so it is a bit more accurate and predictable. 

We use Jenkins and it's notorious for it's less than ideal handling of cloning and checking out repositories. We have had to add additional steps to pull down tags before running python semantic release

**Comment by jacksbox** [comment]
we do not use tags, just depend on the commit message - so it is not only related to the tags.

**Comment by esatterwhite** [comment]
Semantic release uses tags, that's how it understands the previous version. If it can't resolve the last version via repo tags, which it crates, it will assume no previous version and cut a major

**Comment by jacksbox** [comment]
> The way we get and set the new version. Can be commit or tag.
> If set to tag, will get the current version from the latest tag matching vX.Y.Z. This won’t change the source defined in version_variable.
> If set to commit, will get the current version from the source defined in version_variable, edit the file and commit it.
Default: commit

According to the docs ;)

**Comment by esatterwhite** [comment]
ya, it looks to default to commit in code, but my config is pretty basic

```toml
[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = "benchmark/__init__.py:__version__"
branch = "main"
build_command = "poetry build"
```

and this problem exists. I had to add `git fetch origin --tags` before running semantic release to get it to find the right version
