### ISSUE TITLE
Change the type of commits that trigger a release

### ISSUE THREAD

**Issue by FlorentGodin** [python-semantic-release/python-semantic-release#438]
## Description

Hello,

It would be great to make configurable commit types that trigger a release. 

## Use cases

In some cases you want to trigger a release when commiting a refactor or a build. The only way to do this now is, well, to use another type.

## Possible implementation
```toml
[tool.semantic_release]

    [[release_rules]]
        type = "refactor"
        release = "patch"

    [[release_rules]]
        type = "build"
        release = "patch"
```
(Inspirated from : https://github.com/semantic-release/commit-analyzer#release-rules)

**Comment by bernardcooke53** [comment]
@FlorentGodin what commit style are you using?

Looking at the code, there's an undocumented configuration option `parser_angular_patch_types` [here](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/history/parser_angular.py#L39) which you can try setting to [these options](https://github.com/relekang/python-semantic-release/blob/5f28b835b0dbaaeaf2d80c6caaac3d66d4f7d0b0/semantic_release/defaults.cfg#L6) plus whatever extra types you'd like patch-released?

E.g.
```toml
[tool.semantic_release]
...
parser_angular_patch_types = ["fix", "perf", "refactor", "build"]
```

If you want any extra types I believe you have to set them alongside the defaults [here](https://github.com/relekang/python-semantic-release/blob/5f28b835b0dbaaeaf2d80c6caaac3d66d4f7d0b0/semantic_release/defaults.cfg#L2) in `parser_angular_allowed_types`
