### ISSUE TITLE
publish not pushing changes to Github

### ISSUE THREAD

**Issue by vigenere23** [python-semantic-release/python-semantic-release#482]
## The problem

When running the `publish` command, changes occur correctly (updating versions + changelog), but nothing is uploaded to the repo... (excepted for the tag). In fact, no commit is even made (only pending changes). Therefore, the changelog remains empty and the version is not truly bumped... Am I missing a configuration?

Also, no errors, no branch protection, etc. Just a step that seems to be missing in the pipeline.

## Expected behavior

All file changes are uploaded (as a new commit with `chore: release`?)

## Additional context

config (toml):

```toml
[tool.semantic_release]
version_variable = ["modupipe/__init__.py:__version__"]
version_toml = ["pyproject.toml:tool.poetry.version"]
version_source = "tag"
branch = "master"
upload_to_pypi = false
upload_to_release = false
build_command = "poetry build"
```

action:

```yml
...
    steps:
      ...
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # has public_repo scope
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          semantic-release publish --post
```
