### ISSUE TITLE
Option to disable creation of GitHub releases

### ISSUE THREAD

**Issue by vigenere23** [python-semantic-release/python-semantic-release#494]
## The problem

EDIT : I've set `upload_to_release` to `false`, but running `publish` still uploads the changelog and tag to Github releases...

## Expected behavior
To not upload to Github releases.

## Additional context

`pyproject.toml` :

```toml
[tool.semantic_release]
version_variable = ["modupipe/__init__.py:__version__"]
version_toml = ["pyproject.toml:tool.poetry.version"]
version_source = "tag"
branch = "master"
upload_to_pypi = false
upload_to_release = false
build_command = "poetry build"
commit_version_number = true
commit_subject = "chore(release): v{version}"
commit_message = "Released version {version}. See the changelog for changes."
```
