### ISSUE TITLE
Modify Semantic Release Commit Author?

### ISSUE THREAD

**Issue by cmitzel-ncino** [python-semantic-release/python-semantic-release#516]
Howdy -

The `setup.cfg` file has a field that allows for the commit author and email address to be modified, and it appears that the `vcs_helpers.py` function pulls it in [here](https://github.com/python-semantic-release/python-semantic-release/blob/master/semantic_release/vcs_helpers.py#L159). However, when we modified it in our build/test/publish process, the new version commit didn't use the specified author. Upon investigating, the `action.sh` [hardcodes](https://github.com/python-semantic-release/python-semantic-release/blob/master/action.sh#L16) the github actions user into the git config file. 

Am i just missing something? Thanks!

**Comment by bernardcooke53** [comment]
Hey :wave: 

I believe you can specify inputs according to [the workflow syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith) - the PSR action defines the git commit author and email as inputs [here](https://github.com/python-semantic-release/python-semantic-release/blob/master/action.yml#L25#L30). According to the docs:
> When you specify an input in a workflow file or use a default input value, GitHub creates an environment variable for the input with the name INPUT_<VARIABLE_NAME>. The environment variable created converts input names to uppercase letters and replaces spaces with _ characters.

So I think you can set something like 
```yaml
    steps:
      - name: Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          git_committer_name: "someone"
          git_committer_email: "someone@somewhere.org"
```
`action.sh` is just reading in those environment variables that GitHub actions is conveniently creating or assigning defaults to them :slightly_smiling_face: 

Hopefully this works for you :crossed_fingers:

**Comment by bernardcooke53** [comment]
Hey :wave: 

I believe you can specify inputs according to [the workflow syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith) - the PSR action defines the git commit author and email as inputs [here](https://github.com/python-semantic-release/python-semantic-release/blob/master/action.yml#L25#L30). According to the docs:
> When you specify an input in a workflow file or use a default input value, GitHub creates an environment variable for the input with the name INPUT_<VARIABLE_NAME>. The environment variable created converts input names to uppercase letters and replaces spaces with _ characters.

So I think you can set something like 
```yaml
    steps:
      - name: Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          git_committer_name: "someone"
          git_committer_email: "someone@somewhere.org"
```
`action.sh` is just reading in those environment variables that GitHub actions is conveniently creating or assigning defaults to them :slightly_smiling_face: 

Hopefully this works for you :crossed_fingers:
