### ISSUE TITLE
Re-trigger CI/CD on automated push of changes to git

### ISSUE THREAD

**Issue by Seth-Julien-de-Lampon** [python-semantic-release/python-semantic-release#531]
How come the CI/CD pipeline (in the github actions example) is not (re-)triggered when the python-semantic-release package commits a new version to the 'master' branch? Shouldn't a new commit count as a `push` and therefore start a new pipeline execution (which would start an infinite loop)?
```
name: Semantic Release

on:
  push:
    branches:
      - master
```
