### ISSUE TITLE
Build issue when using Python 3.10 in project.

### ISSUE THREAD

**Issue by ItsCalebJones** [python-semantic-release/python-semantic-release#533]
## The problem

Attempt to use Python 3.10.4 in a project built via a GitHub workflow, however the build apparently fails to utilize the venv created with 3.10.4.

```
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: ${{ secrets.PYPI_USERNAME }}
        repository_password: ${{ secrets.PYPI_PASSWORD }}
```

job output
```
 The currently activated Python version 3.9.15 is not supported by the project (^3.10.4).
Trying to find and use a compatible version. 

Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
error: Encountered a bad command exit code!
```

## Expected behavior

Use the environment configured by setup-python.

## Additional context

This project seems to work just fine when running it locally, this only fails when ran via GitHub that uses a system python3.9.5
