### ISSUE TITLE
Hardcoded v-prefix in changelog

### ISSUE THREAD

**Issue by afuetterer** [python-semantic-release/python-semantic-release#561]
Hi there, I just recently started using this great library.

I set the tag_format to `{version}` without the v-prefix.
```toml
[tool.semantic_release]
# ...
tag_format = "{version}"
```
In the changelog headers however there is a hardcoded v-prefix.

```markdown
# Changelog

All notable changes to this project will be documented in this file.

## v0.7.1 (2023-02-19)
### Fix
...
```
There is no way to disable this via another setting, right?

Any help would be appreciated. Thank you.
