### ISSUE TITLE
Semantic release not pushing to git

### ISSUE THREAD

**Issue by rmargar** [python-semantic-release/python-semantic-release#577]
Hi! First of all many thanks for this amazing project. I am trying to integrate semantic release in my CI workflow using GitHub Actions, but it seems that after running `semantic-release --{{ release_type }}`  , the version changes`pyproject.toml` or the new `CHANGELOG.md` are not being pushed to git. However the run shows a correct execution: https://github.com/rmargar/pymavlog/actions/runs/4703632794/jobs/8342371049#step:5:161

I am using the lates version and this is a link to my workflow: https://github.com/rmargar/pymavlog/blob/main/.github/workflows/base-branch.yaml

The seetings I have configured in `pyproject.toml` are:

```toml
[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
version_source = "tag"
build_command = "pip install poetry && poetry build"
repository = "testpypi"
branch = "main"
```
