### ISSUE TITLE
Changelog not commited during publish

### ISSUE THREAD

**Issue by beatreichenbach** [python-semantic-release/python-semantic-release#581]
I'm trying to use python-semantic-release publish to automatically build a release, release notes and changelog. Unfortunately when I publish the changelog gets written after the version bump so it is not included in that tag and I have unstaged changes after the publish finishes. Is there a way to generate the changelog.md before the version bump commit?

Everything else works as expected, the release on GitHub has the correct changes listed, I just wish the changelog was also in the release. Is this the expected behavior?

Here's my pyproject.toml:
```
[tool.semantic_release]
version_variable = "realflare/__init__.py:__version__"
branch = "main"
build_command = "python -m build --sdist --wheel"
upload_to_pypi = false
upload_to_repository = false
```

And this shows how I have unstaged changelog.md changes after the automatically generated commit:

```
>git diff
diff --git a/changelog.md b/changelog.md
index 61f3ce4..88e7843 100644
--- a/changelog.md
+++ b/changelog.md
@@ -1 +1,5 @@
 <!--next-version-placeholder-->
+
+## v0.1.0 (2023-04-22)
+### Feature
+* **benchmark:** Add run function ([`d2796b4`](https://github.com/beatreichenbach/realflare/commit/d2796b4a7b76d4e5e920bfad95533d2658357b05))

>git log
commit 1fde336ff72674536418b61586407d7b6f88ed1c (HEAD -> main, tag: v0.1.0)
Author: semantic-release <semantic-release>                                
Date:   Sat Apr 22 14:20:36 2023 -0700                                     
                                                                           
    0.1.0                                                                  
                                                                           
    Automatically generated by python-semantic-release
```

**Comment by setu4993** [comment]
Ah, turns out it is another setting that I discovered in: https://github.com/python-semantic-release/python-semantic-release/issues/577#issuecomment-1512025933.

This did the trick for me:
```toml
commit_version_number = true
```

**Comment by beatreichenbach** [comment]
> I am running into the same issue. In the past, this worked fine and the changelog and update to `__init__.py` were pushed back to GitHub correctly.

My __init__.py is getting automatically updated because I have: `version_variable = "realflare/__init__.py:__version__"` set.
However `commit_version_number = true` doesn't do anything for me. It's enabled by default and even if I manually set it, changelog does not update. Could you post your config here for reference please @setu4993 ?

**Comment by setu4993** [comment]
Sure, here's my config:

```toml
[tool.semantic_release]
branch = "main"
version_variable = "<package>/__init__.py:__version__"
version_source = "tag"
tag_commit = true
patch_without_tag = true # Always bump the version.
commit_version_number = true
commit_subject = "chore(release): v{version}"
upload_to_release = false
upload_to_repository = true
repository_url = "<repository_url>"
```

For some reason, it wasn't running even though it was the default value. I suspect it's true when `version_source` is set to `commit`, but would need to dig into the code / docs to confirm. Also, the `GH_TOKEN` env var needs to be set since that's the only way for it to push changes (`GITHUB_TOKEN` doesn't work for this).

FWIW, I had to stop doing that and just marked the `__init__.py` version as "doesn't get updated" because I was running into issues with GitHub Actions and branch protections.
