### ISSUE TITLE
Is it possible to also update a Chart.yaml for a Helm Chart?

### ISSUE THREAD

**Issue by jseiser** [python-semantic-release/python-semantic-release#601]
We use this software, to create changelogs, and tag versions in gitlab.  Is it possible to also update the version, in a Chart.yaml for our Helm Charts?

```
❯ tree -L 2
.
├── CHANGELOG.md
├── console
│   ├── charts
│   ├── Chart.yaml
│   ├── README.md
│   ├── templates
│   └── values.yaml
├── Pipfile
├── Pipfile.lock
├── pyproject.toml
└── README.md
```

```
❯ cat console/Chart.yaml 
apiVersion: v2
name: console
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v1.11.0"
```

```
❯ cat pyproject.toml 
[build-system]
requires = ["setuptools"]

[project]
name = "console"
version = "0.1.12"

[tool.semantic_release]
version_toml = ["version_toml = ["pyproject.toml:project.version"]"]
branch = "develop"
build_command = false
upload_to_repository = false
hvcs = "gitlab"
hvcs_domain = "gitlab.company.network"
parser_angular_patch_types = "fix,perf,refactor,build,style"
changelog_sections="feature,fix,breaking,documentation,performance,refactor,build,style,ci,Other"

[tool.setuptools]
packages = []
```

Since `Chart.yaml` is not a toml file, I assume this just isnt possible?

**Comment by bernardcooke53** [comment]
Hey @jseiser - it should absolutely be possible, I suggest you use [version_variable](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#version-variable) as follows:

```toml
[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]  # for the package metadata
version_variable = [
    "console/Chart.yaml:^version: {version}",  # for the chart version
    "console/Chart.yaml:^appVersion: \"{version}\"",  # for the app version
]
```
