### ISSUE TITLE
Error: Not in a valid Git repository

### ISSUE THREAD

**Issue by mike-pisman** [python-semantic-release/python-semantic-release#616]
## The problem

Getting error `Error: Not in a valid Git repository`
For some reason the action does not detect `.git` folder.

## Expected behavior

To build and release the project

## Additional context
```
Run relekang/python-semantic-release@8.0.x
  with:
    github_token: ***
    root_options: -v
    directory: .
    git_committer_name: github-actions
    git_committer_email: github-actions@github.com
    prerelease: false
    commit: true
    push: true
    changelog: true
    vcs_release: true
/usr/bin/docker run --name b1cbc5c19994db167a445f816ce41056fc00b5_dd489d --label b1cbc5 --workdir /github/workspace --rm...

Error: Not in a valid Git repository
```

``` yaml
name: Release Package

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: arc-runner-k8s
    concurrency: release
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@8.0.x
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish package to GitHub Release
      uses: python-semantic-release/upload-to-gh-release@main
      if: ${{ steps.release.outputs.released }} == 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}

```

[#Failed Job](https://github.com/unipoll/API/actions/runs/5416489976/jobs/9846280184)

**Comment by mike-pisman** [comment]
The problem most likely is not related to semantic-release. 
The solution is to install git manually before checkout:
``` yaml
    steps:
    - name: Force Install GIT latest
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install -y git
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
```
