### ISSUE TITLE
`print-version` missing in v8

### ISSUE THREAD

**Issue by shooit** [python-semantic-release/python-semantic-release#638]
## The problem

v8.x no longer supports the `print-version` command or another path to get the current version of the project

## Expected behavior

We have been using the `print-version` command to determine if a release was made in our CI processes. For example,

```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - id: pre-release
        name: get pre-release version
        run: echo "version=$(poetry run semantic-release print-version --current)" >> $GITHUB_OUTPUT
      - name: release
        run: poetry run semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - id: post-release
        name: get post-release version
        run: echo "version=$(poetry run semantic-release print-version --current)" >> $GITHUB_OUTPUT
      - if: steps.pre-release.outputs.version != steps.post-release.outputs.version
        run: my-post-release-jobs
```
