### ISSUE TITLE
GitHub Action Not Publishing Release to PyPi 

### ISSUE THREAD

**Issue by nicrie** [python-semantic-release/python-semantic-release#654]
## The problem

After a successful Pull Request, the GitHub Action triggers python-semantic-release as expected. A new release is created with the correct version number, however **it is not published to PyPi**.  At the beginning of the Github Action, a warning appears which did not show up before:

```bash
Warning: Unexpected input(s) 'repository_username', 'repository_password', valid inputs are ['entryPoint', 'args', 'root_options', 'directory', 'github_token', 'git_committer_name', 'git_committer_email', 'ssh_public_signing_key', 'ssh_private_signing_key', 'prerelease', 'prerelease_token', 'force', 'commit', 'push', 'changelog', 'vcs_release', 'build_metadata']
```

## Expected behavior

New release should be automatically published to PyPi.

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
python --version
pip --version
semantic-release --version
pip freeze
```
- Ubuntu 22
- Python 3.11.4
- pip 23.1.2
- semantic-release: NA (I use Github Actions)
- Poetry (version 1.5.1)

<details>
  <summary>Click me: pip freeze</summary>
  
  ```bash
accessible-pygments==0.0.4
aiobotocore @ file:///home/conda/feedstock_root/build_artifacts/aiobotocore_1678454742153/work
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1686375888575/work
aioitertools @ file:///home/conda/feedstock_root/build_artifacts/aioitertools_1663521246073/work
aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1667935791922/work
alabaster==0.7.13
anyio==3.7.1
appdirs==1.4.4
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
async-generator==1.10
async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1640026696943/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work
Babel==2.12.1
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1687772187254/work
beautifulsoup4==4.12.2
bleach==6.0.0
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1687772839350/work
botocore @ file:///home/conda/feedstock_root/build_artifacts/botocore_1677024021378/work
Bottleneck @ file:///home/conda/feedstock_root/build_artifacts/bottleneck_1678327113810/work
Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1687884021435/work
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1666764686339/work
Cartopy @ file:///home/conda/feedstock_root/build_artifacts/cartopy_1679097946491/work
certifi==2023.5.7
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1671179355965/work
cfgv @ file:///home/conda/feedstock_root/build_artifacts/cfgv_1629909281805/work
cftime==1.6.2
chardet==5.1.0
charset-normalizer==3.1.0
click @ file:///home/conda/feedstock_root/build_artifacts/click_1688732963969/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1674202310934/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
colorcet @ file:///home/conda/feedstock_root/build_artifacts/colorcet_1664843244467/work
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1679481329611/work
commonmark==0.9.1
condastats @ file:///home/conda/feedstock_root/build_artifacts/condastats_1659328576739/work
contourpy @ file:///home/conda/feedstock_root/build_artifacts/contourpy_1686733806710/work
coverage==6.5.0
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1689055976305/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
cytoolz @ file:///home/conda/feedstock_root/build_artifacts/cytoolz_1666829667355/work
dask==2023.6.1
DataProperty==1.0.1
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1680755454898/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml==0.7.1
distlib @ file:///home/conda/feedstock_root/build_artifacts/distlib_1668356257807/work
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1688766508643/work
docutils==0.19
dominate==2.8.0
download-stats==1.3.0
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
fastjsonschema==2.17.1
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1686612785345/work
flake8==4.0.1
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1686578426890/work
frozenlist @ file:///home/conda/feedstock_root/build_artifacts/frozenlist_1667935423514/work
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1686342280219/work
h11==0.13.0
HeapDict==1.0.1
holoviews @ file:///home/conda/feedstock_root/build_artifacts/holoviews_1686298143174/work
httpcore==0.17.3
httpx==0.24.1
identify @ file:///home/conda/feedstock_root/build_artifacts/identify_1683153699653/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
imagesize==1.4.1
importlib-metadata==6.7.0
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1689017639396/work
iniconfig==2.0.0
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1688404758065/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1685727741709/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
Jinja2==3.1.2
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1589369830981/work
joblib==1.3.1
jsonschema==4.18.0
jsonschema-specifications==2023.6.1
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyterlab-pygments==0.2.2
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1666805746048/work
latest-user-agents==0.0.3
linkify-it-py @ file:///home/conda/feedstock_root/build_artifacts/linkify-it-py_1651923627081/work
locket==1.0.0
lz4 @ file:///home/conda/feedstock_root/build_artifacts/lz4_1675806669059/work
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1679584000376/work
markdown-it-py @ file:///home/conda/feedstock_root/build_artifacts/markdown-it-py_1686175045316/work
MarkupSafe==2.1.3
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1678135549780/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
matplotx==0.3.10
mbstrdecoder==1.1.3
mccabe==0.6.1
mdit-py-plugins @ file:///home/conda/feedstock_root/build_artifacts/mdit-py-plugins_1686175351422/work
mdurl @ file:///home/conda/feedstock_root/build_artifacts/mdurl_1639515908913/work
mistune==3.0.1
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1678312711771/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1672339405744/work
munkres==1.1.4
nbclient==0.8.0
nbconvert==7.6.0
nbformat==5.9.0
nbsphinx==0.9.2
nc-time-axis @ file:///home/conda/feedstock_root/build_artifacts/nc-time-axis_1650472822477/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
netCDF4==1.6.4
nodeenv @ file:///home/conda/feedstock_root/build_artifacts/nodeenv_1683892983968/work
numpy==1.24.4
outcome==1.2.0
packaging==23.1
pandas==1.5.3
pandocfilters==1.5.0
panel @ file:///home/conda/feedstock_root/build_artifacts/panel_1688653448811/work
param @ file:///home/conda/feedstock_root/build_artifacts/param_1678790747312/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1681246756246/work
pathvalidate==3.1.0
patsy==0.5.3
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1675487189013/work
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
platformdirs==3.8.0
pluggy==1.2.0
ply==3.11
pooch==1.7.0
pre-commit @ file:///home/conda/feedstock_root/build_artifacts/pre-commit_1686748903002/work
prettytable==3.8.0
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1688565951714/work
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1681775010077/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pyarrow==12.0.1
pycodestyle==2.8.0
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyct==0.4.6
pydata-sphinx-theme==0.13.3
pyflakes==2.4.0
Pygments==2.15.1
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1685514481738/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1687132014935/work
pypistats==1.4.0
pyproj @ file:///home/conda/feedstock_root/build_artifacts/pyproj_1686688441630/work
PyQt5==5.15.7
PyQt5-sip==12.11.0
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1672681471126/work
pyshp @ file:///home/conda/feedstock_root/build_artifacts/pyshp_1659002966020/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
pytablewriter==1.0.0
pytest==7.4.0
python-dateutil==2.8.2
python-dotenv==0.20.0
python-slugify==8.0.1
python-snappy @ file:///home/conda/feedstock_root/build_artifacts/python-snappy_1668089938362/work
pytz==2023.3
pyviz-comms @ file:///home/conda/feedstock_root/build_artifacts/pyviz_comms_1686853987942/work
PyYAML==6.0
pyzmq==25.1.0
referencing==0.29.1
requests==2.31.0
rich==12.5.1
rpds-py==0.8.8
s3fs @ file:///home/conda/feedstock_root/build_artifacts/s3fs_1686345905047/work
scikit-learn==1.3.0
scipy==1.9.3
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1672497695270/work
selenium==4.4.3
shapely @ file:///home/conda/feedstock_root/build_artifacts/shapely_1679081555742/work
sip @ file:///home/conda/feedstock_root/build_artifacts/sip_1681995009210/work
six==1.16.0
sniffio==1.3.0
snowballstemmer==2.2.0
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
soupsieve==2.4.1
Sphinx==6.2.1
sphinx-book-theme==1.0.1
sphinx-copybutton==0.5.2
sphinx-gallery==0.10.1
sphinx_design==0.4.1
sphinxawesome-theme==4.1.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
statsmodels==0.14.0
tabledata==1.3.1
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1616261298899/work
tcolorpy==0.1.3
termcolor==2.3.0
text-unidecode==1.3
threadpoolctl==3.1.0
tinycss2==1.2.1
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
toolz==0.12.0
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
trio==0.21.0
trio-websocket==0.9.2
typepy==1.3.1
typing_extensions==4.7.1
tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1680081134351/work
uc-micro-py @ file:///home/conda/feedstock_root/build_artifacts/uc-micro-py_1608058642472/work
ukkonen @ file:///home/conda/feedstock_root/build_artifacts/ukkonen_1666949003181/work
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1667239931657/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1678635778344/work
virtualenv @ file:///home/conda/feedstock_root/build_artifacts/virtualenv_1687005325630/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webdriver-manager==3.8.6
webencodings==0.5.1
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1677485524200/work
wsproto==1.2.0
xarray @ file:///home/conda/feedstock_root/build_artifacts/xarray_1679589431118/work
-e git+ssh://git@github.com/nicrie/xeofs.git@8e43d155c32ff210ff5e059b99aa5022c3718496#egg=xeofs
xyzservices @ file:///home/conda/feedstock_root/build_artifacts/xyzservices_1684571362432/work
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1685191769397/work
zict @ file:///home/conda/feedstock_root/build_artifacts/zict_1681770155528/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1689027407711/work
  ```
</details>

## Configuration

Please add your `semantic-release` configuration, and if applicable also provide
your `build-system` configuration from `pyproject.toml`.

```toml
[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Logs

Please provide debug logs for the command you are using with the `-vv` flag, e.g.

```shell
semantic-release -vv version
```

If using GitHub actions, ensure the `root_options` contains the `-vv` flag
for verbosity, and attach your workflow definition.

```yml
# Basic workflow for building and testing the pip installation

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab


jobs:

  Quality:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', 3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.5.1
      - name: Configure poetry
        shell: bash
        run: python -m poetry config virtualenvs.in-project true
      - name: View poetry version
        run: poetry --version
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m poetry run flake8 . --exclude .venv --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m poetry run flake8 . --exclude .venv --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python -m poetry run coverage run -m pytest
          python -m poetry run coverage report -m
          python -m poetry run coverage xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

  Release:

    needs: Quality
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python semantic release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_TOKEN }}
```

## Additional context

Project: [xeofs](https://github.com/nicrie/xeofs)
Action without publishing: https://github.com/nicrie/xeofs/actions/runs/5632961260/job/15261422367

Note the last release before the most recent one was successfully published to PyPi. You can find the corresponding action [here](https://github.com/nicrie/xeofs/actions/runs/5509273566/job/14913978570)
