### ISSUE TITLE
How to NOT do the release on Github?

### ISSUE THREAD

**Issue by khamaileon** [python-semantic-release/python-semantic-release#662]
In the latest version of SR, is there any way to NOT do the release on Github? I just want to stop at the tag publication and do the release manually from the tag.

In the previous version, I hacked the script like this : https://github.com/khamaileon/python-semantic-release/commit/9dae4c1f53d62f43f8a231ba6fb8383bba555dc5

**Comment by bernardcooke53** [comment]
Hi @khamaileon :wave: I believe [`--no-vcs-release`](https://python-semantic-release.readthedocs.io/en/latest/commands.html#vcs-release-no-vcs-release) will do this for you

**Comment by khamaileon** [comment]
Hi @bernardcooke53 👋 Thanks for the answer. Do you know how to use that option in a Github action pipeline?

```yaml
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v8.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by khamaileon** [comment]
Found it (well, guessed 😅)
```yaml
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v8.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vcs_release: true
```

**Comment by bernardcooke53** [comment]
Hey @khamaileon - almost!
```yaml
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v8.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vcs_release: false
```
You need to specify `false` to disable the release creation :slightly_smiling_face:
