### ISSUE TITLE
Use in combination with release-drafter

### ISSUE THREAD

**Issue by rvanruitenbeek** [python-semantic-release/python-semantic-release#672]
Is it possible to use the release-drafter release note template instead of the one of python-semantic-release?

I'm trying to use the release flow of python-semantic-release but like the option of release-drafter to format the release in such a way that it solely shows the pull requests and groups the pull requests based on the pull request labels.

This will result in something like:

![Screenshot 2023-08-10 at 15 27 59](https://github.com/python-semantic-release/python-semantic-release/assets/80525424/891c57f8-5f07-4265-a073-6ed2c1cdc12b)

**Comment by bernardcooke53** [comment]
Hey @rvanruitenbeek - if you set `--no-vcs-release`, you can add the `release-drafter` action as a subsequent step in your workflow; the input to the Github Action is `vcs_release: "false"`:

```yaml
---
name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # This action uses Python Semantic Release v8
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v8.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        vcs_release: "false"
    - uses: release-drafter/release-drafter@v5
      if: steps.release.outputs.released == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.release.outputs.tag }}
          version: ${{ steps.release.outputs.version }}

    - name: Publish package distributions to GitHub Releases
      uses: python-semantic-release/upload-to-gh-release@main
      if: steps.release.outputs.released == 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

Looking at https://github.com/release-drafter/release-drafter#action-inputs, you can provide the tag that PSR has created for the release directly.
