### ISSUE TITLE
Default level bump in ^8.0.0 ?

### ISSUE THREAD

**Issue by davidhulick** [python-semantic-release/python-semantic-release#700]
Hello,

I've noticed that `parser_angular_default_level_bump` has been removed in 8.0.0 of Python Semantic Release. Previously we could set `parser_angular_default_level_bump=patch` to increment the patch version number when no valid angular commit tags were found. Is there now a way to do this without writing our own parser?

Thank You!

**Comment by bernardcooke53** [comment]
Hey @davidhulick - you can add

```toml
[tool.semantic_release.commit_parser_options]
default_bump_level = "patch"
```
