### ISSUE TITLE
Version parser error after upgrading to 8.0.8

### ISSUE THREAD

**Issue by chemelli74** [python-semantic-release/python-semantic-release#725]
## The problem

Trying to migrate from 7.34.6 to 8.0.8, following the [documentation](https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html), I experience the following error:

```
pydantic.error_wrappers.ValidationError: 1 validation error for RawConfig
version_toml
  value is not a valid tuple (type=type_error.tuple)
```

## Expected behaviour

Release workflow to complete successfully.

## Environment

from workflow/ci.yml:

```yaml
    env:
      SKIP: no-commit-to-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0

```

## Configuration

Here my config: https://github.com/chemelli74/aiocomelit/pull/15/files

## Additional context

https://github.com/chemelli74/aiocomelit/actions/runs/6361384098/job/17275795206?pr=15

**Comment by zckv** [comment]
Hello,

https://python-semantic-release.readthedocs.io/en/latest/configuration.html#version-variables-list-str

version_variables and version_toml are type List and not string.

```toml
[tool.semantic_release]
branch = "main"
version_toml = ["pyproject.toml:tool.poetry.version"]
version_variable = ["src/aiocomelit/__init__.py:__version__"]
build_command = "pip install poetry && poetry build"
```

**Comment by chemelli74** [comment]
Oh, thx!
Didn't notice this breaking change in the release migration page.

Can you be so kind to tell me if the remaining parts of the config are correctly migrated ?

**Comment by zckv** [comment]
At a glance, the pyproject seems fine now. In your ci.yml, you should use the latest python-semantic-release version (8.1.1). Also, the current version of semantic release can only work on branches. 

There are a number of solutions, personally I use actions/checkout on ref `github.ref_name` to always have a correct HEAD. You can also play with the `on` keyword or set a condition on `github.event_name`.

You can try the full pipeline with the multibranch_release feature:

https://python-semantic-release.readthedocs.io/en/latest/multibranch_releases.html

```toml
[tool.semantic_release.branches.test]
match = "branch_name"
prerelease = true
prerelease_token = "rc"
```

```sh
semantic-release -v version 
```

This will add a "pre-release" in your github release, proving that every thing work correctly.

Now there is a changelog file generated, you can use `with: changelog: false` in the action if you don't want it.
