### ISSUE TITLE
Possible to set `template_dir` to a subdirectory?

### ISSUE THREAD

**Issue by afuetterer** [python-semantic-release/python-semantic-release#754]
Hi there,

I recently tried to clean up my top level / root directory from files, that could be moved.

I tried to move the `templates` into `.github/templates`. I know, that you recommend keeping it top level. But the top level gets really crowded.

How should I set the `template_dir` variable in my config? It does not seem to accept the following:

```toml
# ...
[tool.semantic_release.changelog]
# ...
template_dir = ".github/templates"
# ...
```

Am I doing something wrong here? If I use any name that is in the top level directory, like templates, template, template_dir, it just works.
