### ISSUE TITLE
semantic-release version --vcs-release --no-commit

### ISSUE THREAD

**Issue by tpank** [python-semantic-release/python-semantic-release#761]
I am currently trying to migrate some of our programs from python-semantic-release v7 to v8.
As far as I understand there is is currently no possibility to use the `--vcs-release` flag in combination with the `--no-commit` flag. 

For our previous v7 workflow it was possible to create releases with only a tag and without a commit. 
When looking at the code at https://github.com/python-semantic-release/python-semantic-release/blob/d38d71ef2ae2b3c34066557ddb822385c1730c7f/semantic_release/cli/commands/version.py#L243 I do not understand why these flags are exclusive.

Is there a specific reason for this?

**Comment by codejedi365** [comment]
It's a great question, I was wondering the same thing as I hit the same problem you did.  I opened a PR #752, to provide an alternative workflow to not require a commit action. The PR is still awaiting a review and opened for about a month.

I have not looked specifically into the `--vcs-release` flag, but I did not cover that specifically. If you could post the command & desired behavior that would be helpful or post if my PR would satisfy your workflow as well?

**Comment by tpank** [comment]
My desired workflow would be something like:

```bash
semantic-release version --prerelease --tag --no-commit --vcs-release 
```

That should:
- Compute the new pre-release version, considering versions in git tags in the repository
- Run the build command
- Compile the changelog
- Create a tag
- Add a new Release to GitLab
- Push the tag

**Comment by codejedi365** [comment]
@tpank, luckily for you, #752, was just merged and released as part of `v8.4.0`.  Thanks for the workflow description and I did a simple static analysis of the code and it looks like your command there should work seamlessly.  Just as a point of clarity, your last 2 bullets will be flipped in the order of operations of `python-semantic-release`.

I hope you weren't expecting the CHANGELOG.md to exist prior to your build command (to give your build command the opportunity to bundle in the changelog into the distribution artifact) as currently the order of operations does not support that. The release notes (a changelog about the current version) will however be posted to the GitLab releases section.

**Comment by benedikt-bartscher** [comment]
If i read the code correctly there is currently no way to commit and push a tag but not commit to the branch.

Consider this workflow:
- Compute the new pre-release version, considering versions in git tags in the repository
- Run the build command
- Compile the changelog
- Commit changes
- Create a tag
- Push the tag (but not the branch)
- Add a new Release to GitLab

Am i missing something? I would like to push some versioned assets to the tags only.

**Comment by codejedi365** [comment]
@benedikt-bartscher, at the outset of your question, yes there is not a way to only push the tags but not also commit. We push the commit too. Unless I mis understand, this would cause your tagged commit not in line with your branch history, which seems a bit non-standard.

> I would like to push some versioned assets to the tags only.

This statement is peculiar. Do you mean you only want to commit certain changes to the repository (for example don't commit the changelog but update all the stamped versions)? 

Or you just want to publish built assets (*.whl) to the VCS release section?

**Comment by benedikt-bartscher** [comment]
@codejedi365, thank you for your quick response.
I am using gitlab VCS, running in gitlab CI. Indeed, the idea is a bit non-standard.

I would like to avoid semantic-release to commit to the `main` branch for various reasons. I think the version should not be part of your code. It keeps the commit history cleaner, and avoids conflicts. However, having versioned assets in git can sometimes be useful as well. My workflow tries to combine the best of both worlds.

Consider a simple python project with a pyproject.toml with has `version = "0.0.0"` in the project block. With `--no-commit --tag` Python Semantic Release would release a py package with the correct version in `pyproject.toml` and create a git tag without any commits (still version 0.0.0 in pyproject.toml). I would like python semantic release to commit/push the change in pyproject.toml only to the tag, but not to `main`. The main advantage is to have the same content in the git tag and the python package. This allows to install the python package via poetry git data source while keeping the same release assets available.

**Comment by codejedi365** [comment]
@benedikt-bartscher, I believe this following snippet should create the workflow you desire.

```yml
# .gitlab-ci.yml

release:
    script:
        # Make local changes with implicit `--build`, `--commit`, `--changelog`, `--tag` & `--no-vcs-release`
        - semantic-release version --no-push

        # Manually publish the tag to the repository (tag points at the commit with versioned assets)
        - git push origin "v$(semantic-release version --print)"

        # Create the GitLab Release with Release Notes for previously created tag
        - semantic-release changelog --post-to-release-tag "v$(semantic-release version --print)"

        # [Optional] Reverse your branch if you want to do other stuff on a non-modified main 
        - git reset --hard HEAD~1
```
