### ISSUE TITLE
Issue with package upload to GitLab Package Registry after upgrade to 8.x.x: UserWarning: upload_dists is not supported by Gitlab

### ISSUE THREAD

**Issue by rosaLux161** [python-semantic-release/python-semantic-release#802]
## Issue with package upload to GitLab Package Registry after upgrade to 8.x.x: UserWarning: upload_dists is not supported by Gitlab

**Description:**
Since the update from version 7.34.6 to 8.7.0, the package upload to the GitLab Package Registry is not working in the GitLab-CI.

**Error Message:**

```
$ semantic-release -vv publish
[...]                                                   
/venv/lib/python3.11/site-packages/semantic_release/hvcs/_base.py:88: UserWarning: upload_dists is not supported by Gitlab
  _not_supported(self, "upload_dists")
```

**Previous Working Configuration (with Version 7.34.6):**
- `pyproject.toml`:

```
[tool.poetry]
[...]

[tool.semantic_release]
version_variable = [
    "package_name/__init__.py:__version__",
    "pyproject.toml:version"
]

hvcs = "gitlab"
branch = "main"
upload_to_release = false
upload_to_repository = true
build_command = "pip install poetry && poetry build"
commit_version_number = true
commit_subject = "doc: Changelog {version}"
version_source = "commit"

[...]
```

- `gitlab-ci.yml`:
```
release:
[...]
  variables:
    GITLAB_CI: 'true'
    GL_TOKEN: ${GL_TOKEN}
    hvcs: 'gitlab'
  script:
    - git config user.name xxx
    - git config user.email ${REPOSITORY_USERNAME}@noreply.gitlab.xxx
    - semantic-release publish --verbosity=DEBUG
```

**Attempted Changes for Version 8.x:**
- Modified `pyproject.toml` and `gitlab-ci.yml` as per the updates in version 8.x. Used information from `semantic-release generate-config -f toml --pyproject`, documentation, and [this comment](https://github.com/python-semantic-release/python-semantic-release/issues/659#issuecomment-1651069986).

- `pyproject.toml`:
```
[tool.poetry]
[...]

[tool.semantic_release]
version_variable = [
    "package_name/__init__.py:__version__",
    "pyproject.toml:version"
]


branch = "main"
#upload_to_release = false
#build_command = "poetry build"
commit_version_number = true
commit_subject = "doc: Changelog {version}"
version_source = "commit"

[tool.semantic_release.remote]
name = "origin"
type = "gitlab"
ignore_token_for_push = false
hvcs = "gitlab"
hvcs_domain = "gitlab.xxx"
hvcs_api_domain = "gitlab.xxx/api/v4"


[tool.semantic_release.remote.token]
env = "gitlab"

[tool.semantic_release.publish]
upload_to_vcs_release = true
upload_to_pypi = false
build_command = "poetry build"
```

- `gitlab-ci.yml`: 
```
release:
[...]
  variables:
    GITLAB_CI: 'true'
    GITLAB_TOKEN: ${GL_TOKEN}
    hvcs: 'gitlab'
  script:
    - git config user.name xxx
    - git config user.email ${REPOSITORY_USERNAME}@noreply.gitlab.xxx
    - git branch --force $CI_COMMIT_BRANCH $CI_COMMIT_SHA
    - git checkout $CI_COMMIT_BRANCH
    - semantic-release -vv version
    - semantic-release -vv publish

```

**Current Status:**
- Version number generation and changelog push are successful.
- The push to the GitLab Package Registry fails with the error messagethat GitLab is not supported.

**Observations:**
- There is no `upload_dists` function in the GitLab class ([documentation link](https://python-semantic-release.readthedocs.io/en/latest/api/semantic_release.hvcs.html)).
- **No support** is mentioned [here](https://github.com/python-semantic-release/python-semantic-release/issues/767#issuecomment-1848275065).

**Confusion:**
I am confused as it worked previously with version 7.34.6, and now it fails in a newer version. The documentation mentions that not all features are supported for all HVCS providers, but does this imply that GitLab is **no longer** supported?
