### ISSUE TITLE
Wrong way to add asset ?

### ISSUE THREAD

**Issue by jeremy-bepoix** [python-semantic-release/python-semantic-release#859]
Hi, 
I think I've set up my action incorrectly, because I can't upload custom assets during a release as if it couldn't find the path to the zip file.
The version bump works fine, as does the changlelog, but not the asset upload.
On github-action.yaml i call python script `create_package.py` for creating a build store in mypackage/package/build-version.zip

[As i can see](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#tool-semantic-release-publish), to upload an asset, i need to add `dist_glob_patterns` but when i'v got a warning `No release corresponds to tag , can't upload dists`

pyproject.toml
```yaml
[tool.poetry.dependencies]
python = ">=3.9.1,<3.10"

[tool.semantic_release]
logging_use_named_masks = true
tag_format = "v{version}"
commit_parser = "angular"
commit_author = "github-actions <actions@github.com>"
commit_message = "release: {version} [skip ci]"
major_on_zero = true
version_toml = ["pyproject.toml:tool.poetry.version"]
version_variables = ["version.py:__version__"]

[tool.semantic_release.commit_parser_options]
allowed_tags = [
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "style",
    "refactor",
    "test",
]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease = false
prerelease_token = "rc"

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
token = { env = "GH_TOKEN" }

[tool.semantic_release.publish]
dist_glob_patterns = ["package/*"]
upload_to_vcs_release = true
```

github-action.yaml
```yaml
name: Release
on:
  push:
    branches:
      - main
env :
  PACKAGE_NAME: myPackage
jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create package
      run: |
        python create_package.py
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to gitHub release
      uses: python-semantic-release/upload-to-gh-release@main
      if: ${{ steps.release.outputs.released }} == 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}
```
Runner logs:
```log
/usr/bin/docker run --name d14797b480a5bbbf1641d1b21e1fbb1c42b3cc_34e577 --label d14797 --workdir /github/workspace --rm -e "PACKAGE_NAME" -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "INPUT_GITHUB_TOKEN" -e "INPUT_TAG" -e "INPUT_ROOT_OPTIONS" -e "INPUT_DIRECTORY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mypackage":"/github/workspace" d14797:b480a5bbbf1641d1b21e1fbb1c42b3cc
[semantic_release.cli.util] INFO                  util.py:78
                    util.load_raw_config_file: Loading configuration            
                    from pyproject.toml                                         
           INFO     [semantic_release.cli.config] INFO             config.py:[23](#step:8:24)8
                    config.select_branch_options: Using group                   
                    'main' options, as '(main|master)' matches                  
                    'main'                                                      
           INFO     [semantic_release.cli.commands.publish] INFO   publish.py:48
                    publish.publish: Uploading distributions to                 
                    release                                                     
           WARNING  [semantic_release.hvcs.github] WARNING         github.py:[25](#step:8:26)2
                    github.upload_dists: No release corresponds to              
                    tag , can't upload dists
```
have got an idea ?

**Comment by jeremy-bepoix** [comment]
If i run in debug mode `dist_glob_patterns` try to find in `dist/*` not in `package/*`
```
DEBUG    [semantic_release.hvcs.github] DEBUG           helpers.py:45
                    helpers._wrapper:                                           
                    upload_dists(<semantic_release.hvcs.github.Git              
                    hub object at 0x7f[74](#step:8:75)ad0[78](#step:8:79)cd0>, tag='v0.1.23',               
                    dist_glob='dist/*')                                         
           DEBUG    [semantic_release.hvcs.github] DEBUG           helpers.py:45
                    helpers._wrapper:                                           
                    get_release_id_by_tag(<semantic_release.hvcs.g              
                    ithub.Github object at 0x7f74ad078cd0>,                     
                    tag='v0.1.23')                                              
           DEBUG    [semantic_release.hvcs.github] DEBUG            github.py:74
                    github._get_repository_owner_and_name: getting              
                    repository owner and name from environment                  
                    variables                                                   
           DEBUG    [urllib3.connectionpool] DEBUG        connectionpool.py:1055
                    connectionpool._new_conn: Starting                          
                    new HTTPS connection (1):                                   
                    api.github.com:443                                          
           DEBUG    [urllib3.connectionpool] DEBUG         connectionpool.py:549
                    connectionpool._make_request:                               
                    [https://api.github.com:443](https://api.github.com/) "GET                             
                    /repos/project/myproject/releases/tags/v0.1.23 HTTP/1.1" 200                      
                    None                                                        
           DEBUG    [semantic_release.hvcs.github] DEBUG           helpers.py:56
                    helpers._wrapper: Github.get_release_id_by_tag              
                    -> 146433454                                                
           DEBUG    [semantic_release.hvcs.github] DEBUG           helpers.py:56
                    helpers._wrapper: Github.upload_dists -> 0
```

**Comment by jeremy-bepoix** [comment]
Finnaly i' don't know why but `dist_glob_patterns = ["dist/*"]` seems hard coded ? because no matter what path I give it, it will always look in /dist*.
So i let `dist_glob_patterns = ["dist/*"]` in pryproject.toml then create a folder `dist` and copy my build on it. 
see : Create package
```
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create package
      run: |
        python create_package.py
        mkdir -p dist && cp package/*.zip ./dist
    - name: Upload to gitHub release
      id: github-release
      if: steps.release.outputs.released == 'true'
      uses: python-semantic-release/upload-to-gh-release@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}
```
