### ISSUE TITLE
Add config option to disable Changelog

### ISSUE THREAD

**Issue by KennethEnevoldsen** [python-semantic-release/python-semantic-release#874]
## Description

I would like to be able to not have a CHANGELOG.md file. This could e.g. be done by setting the Changelog to `""` or creating a custom flag.

## Use cases

Some repositories only want the version management of semver without the auto updated changelog.

## Possible implementation

This could e.g. be done by setting the Changelog to `""` or creating a custom flag. I believe it is already possible using:

```
[tool.semantic_release.changelog]
# no changelog:
changelog_file = "/dev/null"
```
which is OS specific.

**Comment by KennethEnevoldsen** [comment]
But can I also use that option within the GitHub actions?

**Comment by codejedi365** [comment]
> But can I also use that option within the GitHub actions?

Docs: https://python-semantic-release.readthedocs.io/en/latest/github-action.html#command-line-options

Did you try:

```yml
- name: Python Semantic Release
  uses: python-semantic-release/python-semantic-release@v8.0.0
  with:
    changelog: "false"
```
