### ISSUE TITLE
`version_toml` config to support complex dependencies format in `project.toml`

### ISSUE THREAD

**Issue by aaaaahaaaaa** [python-semantic-release/python-semantic-release#883]
## Description

It would be great if the `version_toml` config could allow to update the version number of dependencies (e.g. under `[tool.poetry.dependencies]`), which have a more complex form.

Example:
```toml
[tool.poetry.dependencies]
my-package = { version = "1.0.0", source = "my-source" }  # <- target this

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.poetry.version",
    "pyproject.toml:tool.poetry.dependencies.my-package",
]
```

Currently, the replacement does work with the example above, but would replace the entire line with:
```toml
[tool.poetry.dependencies]
my-package = "2.0.0"
```

## Use cases

Why targeting dependencies in the first place? We're using `python-semantic-release` in the context of a monorepo, containing multiple sub Poetry packages. Some of those sub packages have mutual dependencies. Our strategy is to increment the version number in sync between all the packages, and therefore, we would like to have the newly computed version to be reflected in the dependencies for a robust resolution.

## Possible implementation

Maybe introducing a new token to query json values. E.g. (`$`):
```toml
version_toml = [
    "pyproject.toml:tool.poetry.dependencies.my-package$version",
]
```

**Comment by codejedi365** [comment]
@aaaaahaaaaa, thank you for bringing up this lack of functionality. It seems reasonable to make sure this modification is available. I'll take a look soon.

**Comment by codejedi365** [comment]
@aaaaahaaaaa, actually this is feature already works, you just need to add one more index.  Your toml shorthand that uses brackets is an equivalent to a TOML table which gets parsed into a python dictionary.  This means all you need to do is add the additional key to the configuration. I just tested this with a successful replacement.

```toml
[tool.poetry.dependencies]
my-package = { version = "1.0.0", source = "my-source" } 

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.poetry.dependencies.my-package.version",    # <- add version key
]
```
