### ISSUE TITLE
Support tag in GH action config

### ISSUE THREAD

**Issue by rantoniuk** [python-semantic-release/python-semantic-release#906]
`--commit` and `--tag` are supported separately, i.e. I can run a release on a non-PyPi project that does not require any source code changes and just create a tag and pushing it when doing a release.

This is possible in the tool:
https://python-semantic-release.readthedocs.io/en/latest/commands.html#tag-no-tag

but it's not possible in GH action, as there is only `commit` option available:
https://github.com/python-semantic-release/python-semantic-release/blob/master/action.yml#L53
and no `tag` option.

**Comment by codejedi365** [comment]
That is a good catch, thank you. I did need to up date it.  It is not easy keeping up with the action config as there isn't real testing for it.

**Comment by codejedi365** [comment]
@rantoniuk , would you try out this fix and see if it works for you?

```yml
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: codejedi365/python-semantic-release@fix/gha-missing-tag-option
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit: false
        tag: true
        # ...
```
