### ISSUE TITLE
semantic-release publish is deleting files from dist/* directory

### ISSUE THREAD

**Issue by surya-sigtech** [python-semantic-release/python-semantic-release#910]
## The problem

When running `semantic-release publish` in our CI workflow using Github Actions, the command is unexpectedly deleting files within the dist/ directory. It's worth noting that this directory is untracked and listed in our .gitignore file.

## Expected behavior

We expect semantic-release publish to execute successfully without affecting any untracked files, simply pushing the new release.

## Environment

- We are using poetry as a build tool. 

```shell
python --version
3.11.8
semantic-release --version
7.32.2
poetry --version
1.5.1
```

## Configuration

```toml
[tool.semantic_release]
version_variable = [
    "{project_dir}/__version__.py:__version__",
    "pyproject.toml:version"
]
branch = "master"
changelog_components = "custom_changelog_generator.custom_changelog_generator"
upload_to_pypi = false
upload_to_release = false
commit_author= "xxx"
hcvs = "github"
build_command = "poetry build"
```

## Logs

Only info logs are available.

```text
Current version: 7.0.5, Current release version: 7.0.5
Bumping with a patch version to 7.0.6
Pushing new version
warning: Missing token: cannot post changelog to HVCS
Publish has finished
```

## Additional Information:
The semantic-release command is executed in our Github Action step using the following command: 
```bash
python -m poetry run semantic-release publish
```
