### ISSUE TITLE
Preferred way to update other files with "next" version and date using GHA

### ISSUE THREAD

**Issue by afuetterer** [python-semantic-release/python-semantic-release#912]
I know that the `version_pattern` option has been [deprecated](https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html#version-pattern).

What is the preferred way to do this with `sed`?

I would like to do the following:

- use the GitHub Action of python-semantic-release
- get the "next" version and update a text file
- have the updated version of the text as part of the tag/release commit, like the updated changelog

So far I am manually pip installing the semantic-release library to do this, but this feels wrong.

```yaml
# checkout
# pip install semantic-release
- run: |
    sed -i "s/^version: .*/version: $(semantic-release version --print)/" CITATION.cff
    sed -i "s/^date-released: .*/date-released: $(date "+%Y-%m-%d")/" CITATION.cff
    git add CITATION.cff
# run semantic-release github action
```

How should I do this? Can you give me a hint?

**Comment by codejedi365** [comment]
Your approach ultimately gets the job done, but I understand your concern that you have a couple variations of dependencies in your use which is less than ideal.  Unfortunately both my suggestions below require 2 executions of python-semantic-release and depending on your repo size this is not performant.  I am aware of numerous performance flaws and am working to solve many of them. I have not tested the following scripts but I hope this gives you a better start point.

### Option 1

You could use the release action just to identify the version without making changes and then run your sed command and release.  

```yml
# .github/workflows/release.yml
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup | Repo Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: psr-check
        uses: python-semantic-release@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          root_options: "-v --noop"

      - run: |
          sed -i 's/^version: .*/version: ${{ steps.psr-check.outputs.version }}/' CITATION.cff
          sed -i "s/^date-released: .*/date-released: $(date "+%Y-%m-%d")/" CITATION.cff
          git add CITATION.cff

      - name: Python Semantic Release
        uses: python-semantic-release@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

### Option 2

A more succinct way to approach it would be to integrate it into your `build_command` definition. It would be messy to be placed directly in your toml but this could be done as it is passing this string to a subprocessed shell.  Rather I would recommend creating a simple `build.sh` and call that from the `build_command`.

```sh
#!/bin/bash
# FILE: scripts/build.sh

NEXT_VERSION="$(semantic-release version --print)"
sed -i "s/^version: .*/version: $NEXT_VERSION/" CITATION.cff
sed -i "s/^date-released: .*/date-released: $(date "+%Y-%m-%d")/" CITATION.cff
git add CITATION.cff

python3 -m build
```

```sh
# pyproject.toml
[tool.semantic_release]
build_command = "sh ./scripts/build.sh"
```

```yml
# .github/workflows/release.yml
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup | Repo Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: python-semantic-release@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

I do think this leads me to identify that we should pass the new version via environment variable or string replace of the build_command string but that is not yet provided.
