### ISSUE TITLE
How to set up flags in the pyproject.toml file?

### ISSUE THREAD

**Issue by andreasciamanna** [python-semantic-release/python-semantic-release#917]
I can't find how to set flags such as `push`/`no-push`, `--tag`/`--no-tag`, etc. in the `pyproject.toml` file.

I've tried that, with no avail:

```toml
[tool.semantic_release]
# ...
push = false
tag = true
commit = true
change_log = true
```

I know I can provide the flags in the CLI, but this is an unsafe option when several developers work on the same project: they may forget to set the correct flags.

Adding a script or a Makefile would only add complexity and more changes for developers to use the wrong tool.

I would like these to be enforced in the configuration file, which is safer as developers will be less prone to make changes there accidentally.
