### ISSUE TITLE
GHA of PRS 9.7.0 does not respect `git_committer_name` and `git_committer_email` anymore

### ISSUE THREAD

**Issue by afuetterer** [python-semantic-release/python-semantic-release#918]
## The problem

I used the GHA of PSR 9.6.0 with `git_committer_name` and `git_committer_email` configured to let the release commit be from the GitHub bot with its avatar icon. Updating to PSR 9.7.0 now I get commits made by `semantic-release <semantic-release>`. Do I need to change something or is this a bug in 9.7.0?

## Expected behavior

I expected the committer to still be `github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>`.

## Environment

Do you need this information, if I have a problem using the GHA?
See: https://github.com/afuetterer/services-test4

Please state which OS you are using and provide the output of the following commands:

```shell
python --version
pip --version
semantic-release --version
pip freeze
```

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.

## Configuration

```toml
[tool.semantic_release]
commit_message = "chore: release {version}\n\nAutomatically generated by python-semantic-release [skip ci]"
logging_use_named_masks = true
major_on_zero = false
tag_format = "{version}"
version_toml = ["pyproject.toml:project.version"]
build_command = """
sed -i "s/^version: .*/version: $NEW_VERSION/" CITATION.cff
sed -i "s/^date-released: .*/date-released: $(date "+%Y-%m-%d")/" CITATION.cff
git add CITATION.cff
python -m pip install "build[uv]>=1.2.1"
python -m build --installer=uv
"""
changelog.template_dir = ".github/templates"

[tool.semantic_release.changelog.environment]
keep_trailing_newline = true
```

```yaml
  - name: Create semantic release
    id: semantic-release
    uses: python-semantic-release/python-semantic-release@76b17cc32ac75b87ae301df6d302f71c5eefa9b3 # v9.7.0
    with:
      github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      git_committer_name: github-actions[bot]
      git_committer_email: 41898282+github-actions[bot]@users.noreply.github.com
      root_options: -vv
```

## Logs

See: https://github.com/afuetterer/services-test4/actions/runs/8966931525/job/24623457653

Note: This is only a dummy project to test things out.

## Additional context

Example commits from before and after updating to 9.7.0:

```
commit 43d08d648a44cd6e2d0d376fff911b0fc535580c (HEAD -> main, tag: 0.19.3, origin/main)
Author: semantic-release <semantic-release>
Date:   Mon May 6 09:27:30 2024 +0000

    chore: release 0.19.3
    
    Automatically generated by python-semantic-release [skip ci]

# update to PSR 9.7.0 ...

commit f2c05e6db68f83a3c1add6265634837368e955eb (tag: 0.18.0)
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Mon May 6 08:49:57 2024 +0000

    chore: release 0.18.0
    
    Automatically generated by python-semantic-release [skip ci]
```
