### ISSUE TITLE
Allow signing the tags that are created

### ISSUE THREAD

**Issue by nfelt14** [python-semantic-release/python-semantic-release#936]
## Description

It would be nice if the tags that are created by the GitHub Action would be able to be signed when commit signatures are enabled.

## Use cases

This would be useful in every case where a new tag is created using the GitHub Action. It would add an extra indicator that the tag is official.

## Possible implementation

Simply add a line of code to turn on tag auto-signing when commit auto-signing is enabled in the GitHub action.

``git config --global tag.gpgSign true``

**Comment by codejedi365** [comment]
@nfelt14, thanks for providing a solution.  Would you try this out for me as I don't have a working example to test on and let me know if this works?

Adjust your action to use the following to test the fix:

```yml
job:
  release:
    steps:
      # ...
      - name: Python Semantic Release
        uses: codejedi365/python-semantic-release@feat/gha-sign-tags
```
