### ISSUE TITLE
The files specified in dist_glob_patterns are not uploaded to GitHub.

### ISSUE THREAD

**Issue by JCHacking** [python-semantic-release/python-semantic-release#943]
## The problem
The files specified in dist_glob_patterns are not uploaded to GitHub.

## Expected behavior
When I configure dist_glob_patterns with dist/* I expect each of the files contained therein to be uploaded.

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
Windows 10

python --version
Python 3.12.3

pip --version
pip 24.0 from C:\Users\jcmencia\PycharmProjects\GitHubPoc\py_seed\venv\Lib\site-packages\pip (python 3.12)

semantic-release --version
semantic-release, version 9.8.0

pip freeze
annotated-types==0.7.0
arrow==1.3.0
attrs==23.2.0
Babel==2.15.0
boolean.py==4.0
build==1.2.1
CacheControl==0.14.0
certifi==2024.2.2
chardet==5.2.0
charset-normalizer==3.3.2
cleo==2.1.0
click==8.1.7
click-option-group==0.5.6
colorama==0.4.6
coverage==7.5.3
crashtest==0.4.1
cyclonedx-bom==4.4.3
cyclonedx-python-lib==7.4.0
defusedxml==0.7.1
distlib==0.3.8
dotty-dict==1.3.1
dulwich==0.21.7
fastjsonschema==2.19.1
filelock==3.14.0
fqdn==1.5.1
ghp-import==2.1.0
gitdb==4.0.11
GitPython==3.1.43
griffe==0.45.2
idna==3.7
importlib_resources==6.4.0
iniconfig==2.0.0
installer==0.7.0
isoduration==20.11.0
jaraco.classes==3.4.0
Jinja2==3.1.4
jsonpointer==2.4
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
keyring==24.3.1
license-expression==30.3.0
lxml==5.2.2
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mergedeep==1.3.4
mkdocs==1.6.0
mkdocs-autorefs==1.0.1
mkdocs-gen-files==0.5.0
mkdocs-get-deps==0.2.0
mkdocs-literate-nav==0.6.1
mkdocs-material==9.5.25
mkdocs-material-extensions==1.3.1
mkdocs-section-index==0.3.9
mkdocstrings==0.25.1
mkdocstrings-python==1.10.3
more-itertools==10.2.0
msgpack==1.0.8
mypy==1.10.0
mypy-extensions==1.0.0
packageurl-python==0.15.0
packaging==24.0
paginate==0.5.6
pastel==0.2.1
pathspec==0.12.1
pexpect==4.9.0
pip-requirements-parser==32.0.1
pkginfo==1.10.0
platformdirs==4.2.2
pluggy==1.5.0
poethepoet==0.26.1
poetry==1.8.3
poetry-core==1.9.0
poetry-plugin-export==1.8.0
ptyprocess==0.7.0
py-serializable==1.0.3
-e git+https://github.com/JCHacking/py_seed.git@06597be47d8281c89ec2cf454805ce9489e0873d#egg=py_seed
pydantic==2.7.2
pydantic_core==2.18.3
Pygments==2.18.0
pymdown-extensions==10.8.1
pyparsing==3.1.2
pyproject_hooks==1.1.0
pytest==8.2.1
pytest-asyncio==0.23.7
pytest-cov==5.0.0
pytest-html==4.1.1
pytest-metadata==3.1.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-gitlab==4.6.0
python-semantic-release==9.8.0
pywin32-ctypes==0.2.2
PyYAML==6.0.1
pyyaml_env_tag==0.1
rapidfuzz==3.9.1
referencing==0.35.1
regex==2024.5.15
requests==2.32.3
requests-toolbelt==1.0.0
rfc3339-validator==0.1.4
rfc3987==1.3.8
rich==13.7.1
rpds-py==0.18.1
ruff==0.4.6
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sortedcontainers==2.4.0
tomli==2.0.1
tomlkit==0.12.5
trove-classifiers==2024.5.22
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.0
uri-template==1.3.0
urllib3==2.2.1
virtualenv==20.26.2
watchdog==4.0.1
webcolors==1.13
```

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.
Poetry (version 1.8.3)

## Configuration
```toml
[tool.semantic_release]
allow_zero_version = false
build_command = "poetry build"
build_command_env=[]
commit_message = "chore: Release new version {version}"
commit_parser = "angular"
tag_format = "v{version}"
version_toml = [
    "pyproject.toml:tool.poetry.version"
]

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "Example <example@gmail.com>"

[tool.semantic_release.branches.main]
match = "main"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "style", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.changelog]
template_dir = "scripts/templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = ["chore: Release new version *"]

[tool.semantic_release.changelog.environment]
trim_blocks = true

[tool.semantic_release.remote]
type = "github"
token = { env = "GITHUB_TOKEN" }
```
