### ISSUE TITLE
Running github actions after python-semantic-release?

### ISSUE THREAD

**Issue by justin-pierce** [python-semantic-release/python-semantic-release#951]
I want to run python-semantic-release, then deploy if there's a new release -- I want to deploy the commit created by python-semantic-release. In my test repo, so far I've got it set up as two jobs. 

```yaml
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    concurrency: semantic-release
    outputs:
      released: ${{ steps.semrel.outputs.released }}
      version: ${{ steps.semrel.outputs.version }}
      tag: ${{ steps.semrel.outputs.tag }}
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      id: semrel
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog: "false"


  post-release:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.released == 'true'
    steps:
    - run: |
        echo RELEASED: ${{ needs.semantic-release.outputs.released }}: ${{ needs.semantic-release.outputs.version }}: ${{ needs.semantic-release.outputs.tag }}
    - uses: actions/checkout@v4
    - run: |
        cat info.toml
```

post-release only runs if python-semantic-release's `released` output is `true`. 

![Screen Shot 2024-06-11 at 11 36 57](https://github.com/python-semantic-release/python-semantic-release/assets/2170989/3de98a47-cc82-42b7-8d74-b3a648a47ca2)

Unfortunately, this job isn't seeing the changes made from the commit python-semantic-release creates during release (it bumped to 0.5.0 but it still sees 0.4.0 in the toml targeted by `version_toml`). Presumably this is part of github actions design (all jobs based off same commit). 

So I thought maybe I could have a github action check if it's a release commit vs a commit that triggers a release, but the new release commit isn't triggering github actions. Not seeing something like [skip ci] in the commit message so not sure why -- do commits created by actions automatically skip ci? 

Is there a best practices for doing what I want? I want to deploy the code as it is after the commit created by python-semantic-release.

Edit: Away from PC rn but when I get back I'll try specifying the new tag when I use the checkout action in the post release job.
