### ISSUE TITLE
Add support for adding .cff-file variable in version_variables

### ISSUE THREAD

**Issue by geddy11** [python-semantic-release/python-semantic-release#962]
When you have a [CITATION.cff file](https://citation-file-format.github.io/) in a python project, the package version is stored in a variable `version` in this file which needs to be updated for each release, i.e.:
```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/1234-5678-9101-1121
title: "My Research Software"
version: 2.0.4
identifiers:
  - type: doi
    value: 10.5281/zenodo.1234
date-released: 2021-08-11
```

Request support for adding CITATION.cff to `version_variables` list.

**Comment by codejedi365** [comment]
@geddy11, the version variables specification is fairly flexible, you should be able to use `filename:variable` like this:

```toml
[tool.semantic_release]
version_variables = [
    "CITATION.cff:version",
]
```

Since the `citation.cff` is valid yaml, it should work as it did over in #601. The minor nuance is that you likely will need to wrap the version value in quotes which is still valid yaml but it makes the regex match properly.
