### ISSUE TITLE
Adding allowed_tags not working - Angular or Scipy parser

### ISSUE THREAD

**Issue by pbhasin** [python-semantic-release/python-semantic-release#992]
## Question

Hi,
I am trying to add a keyword (tag) to allowed_tags to bump to major, minor or patch version and it's not working.  I am using Gitlab CI.  Whenever I commit the code with comment like "feat" or "fix" (using angular parser), I do get the version bump accordingly.  Likewise if I use scipy and have keyword like "API" in my commit, i do get a major release version bump.  However, when I put in comment like "BREAKING CHANGE" or "BREAKING CHANGE:  some description", it doesn't bump version to Major.  I tried both using both Angular and Scipy as parser and adding keywords to allowed_tags but still I can only bump the version whether major, minor or patch using the keywords defined in allowed_tags.  If I add keyword of my own, it doesn't work.  Ultimately, I would like to add "major, minor, patch" as the keywords to bump appropriate version.  I am pasting my pyproject.toml file with both using angular and scipy as parsers and also my .gitlab-ci.yml file for gitlab ci.

BTW:  I have tried using both 9.8.5 release and 9.8.6 release.

### Configuration
Below is configuration for Angular parser:  pyproject.toml
```
[tool.semantic_release]
version_variables = ["setup.py:__version__", "semver.py:__version__"]
commit_parser = "angular"
tag_format = "v{version}"
major_on_zero = true
allow_zero_version = true
commit_message = "{version}\n\nAutomatically generated by semantic-release"

[tool.semantic_release.commit_parser_options]
allowed_tags = [
    "build",
    "chore",
    "major",     <-------- i added this.
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "style",
    "refactor",
    "test",
]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
major_tags = ["major"] <------------------ i added this.  Don't know if it's even supported.

[tool.semantic_release.remote]
type = "gitlab"
branch = "main"
upload_to_repository = true
```

This is pyproject.toml using "scipy".
```
[tool.semantic_release]
version_variables = ["setup.py:__version__", "semver.py:__version__"]
commit_parser = "scipy"
tag_format = "v{version}"
major_on_zero = true
allow_zero_version = true
commit_message = "{version}\n\nAutomatically generated by semantic-release"

[tool.semantic_release.commit_parser_options]
allowed_tags = [
    "API",
    "MAJOR",
    "DEP",
    "ENH",
    "REV",
    "BUG",
    "MAINT",
    "BENCH",
    "BLD",
    "DEV",
    "DOC",
    "STY",
    "TST",
    "REL",
    "FEAT",
    "TEST",
]
major_tags = ["API","MAJOR"]
minor_tags = ["DEP", "DEV", "ENH", "REV", "FEAT"]
patch_tags = ["BLD", "BUG", "MAINT"]

[tool.semantic_release.remote]
type = "gitlab"
branch = "main"
upload_to_repository = true

[tool.semantic_release.remote.token]
env = "GITLAB_TOKEN"
```

Here is my Gitlab CI:

```
bump_version:
  image:  python:3.9
  before_script:
    - apt-get update && apt-get -y install git
    - pip install -r ./requirements.txt
    - git config --global user.name "Bot"
    - git config --global user.email "bot@bot.com"
    - git checkout "$CI_COMMIT_REF_NAME"
  script:
    - semantic-release -vv --config "pyproject.toml" version
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
```
