### ISSUE TITLE
Github Actions - Include submodules in assets

### ISSUE THREAD

**Issue by ahamboeck** [python-semantic-release/python-semantic-release#993]
## Question

Is there a way to include submodules inside the created asset zips? They are included but are empty.

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release.remote]
type = "github"
token = { env = "GH_TOKEN" }

[tool.semantic_release]
branch = "main"
version_variable = [
    "foo.bar"
]
commit_message = "chore(release): release {version} [skip ci]\n\nAutomatically generated by python-semantic-release"
assets = [
    "some submodules here"
]
[tool.semantic_release.upload_to_pypi]
enabled = false
```
<summary>GitHub Action YML</summary>
```yml
name: Release Workflow

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  setup-and-release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_CLONE_PAT }}
          submodules: 'recursive'
          fetch-depth: 0 
          persist-credentials: false 

      - name: Explicitly set HTTPS URLs for submodules and sync
        run: |
          git config submodule.modules/foo.bar"
  
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive modules/foo-bar
          
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install python-semantic-release

      - name: Show current Git status
        run: |
          git status
          git log --oneline -n 5

      - name: List contents
        run: ls -R
              
      - name: Run Semantic Release
        run: semantic-release version
        env:
          GH_TOKEN: ${{ secrets.BACKEND_WRITER_PAT }}  

```
</details>
